.github/workflows/openai_code_review.yml
GitHub Actionsのワークフローにおいて、`anc95/ChatGPT-CodeReview`のバージョンを明示的に指定し、安定性と予測可能性を高めることを目指しています。
- `.github/workflows/openai_code_review.yml`ファイルにおいて、`anc95/ChatGPT-CodeReview`アクションのバージョンを`@v1.0.11`に固定しました。
なし
特定バージョンの利用による影響やワークフローの動作についての確認をお願いします。
- ワークフローが新しい設定で正常に動作するかどうかの確認が必要です。 
#4 
ワークフローのテスト結果やログのスクリーンショットを添付してください。
---
=> GitHub ActionsでChatGPT-CodeReviewのバージョンをv1.0.11に更新

go.mod
このPRは、Swaggerドキュメントにアクセスできない問題を解決することを目的としています。モジュール名が`minori`から`github.com/YJU-OKURA/project_minori-gin-deployment-repo`に変更され、パスの不一致が原因で発生していた問題を修正します。
- `go.mod`ファイル内のモジュール名を`minori`から`github.com/YJU-OKURA/project_minori-gin-deployment-repo`に変更しました。
- Swaggerドキュメントへのアクセス問題を解決しました。
なし
モジュール名の変更がプロジェクト全体に与える影響に注目してください。
- 変更後、Swaggerドキュメントが正常に表示されるかどうかを確認してください。
- 関連するIssue: #9
---
=> Swaggerドキュメントのパス問題を解決するためのモジュール名の変更

.github/workflows/ci.yml
* CI/CDプロセスの構築とDockerを使用した自動デプロイメントの設定を行い、効率的な開発フローの確立を目指します。GolangバックエンドとMySQLデータベースの自動デプロイを実現するための設定を含みます。
* Dockerfileの作成とGitHub Actionsを使用したCI workflowの構成を追加しました。これにより、コードのマージ時に自動でDockerイメージがビルドされ、デプロイが行われます。
* なし
* DockerfileとCI workflowの設定に特に注目していただきたいです。また、セキュリティ面や最適化の観点からのフィードバックも求めています。
* Dockerイメージのビルドとデプロイプロセスの検証が必要です。また、新しいCI設定が想定通りに動作するかの確認も必要です。
* #18 
> （スクリーンショットやビデオなどがあればここに追加）
=> CIプロセスとDockerデプロイメントの設定を追加

.github/workflows/ci.yml
* これまでのCIプロセスでは、全てのDockerイメージが「`latest`」タグで統一的に管理されていました。このPRでは、より詳細なバージョニングを実現するために、日付ベースのタグ付け方式への移行を提案します。これにより、各ビルドのバージョンを正確に追跡し、管理することが可能になります。
* `GitHub Actions`ワークフローにおいて、イメージタグを日付と時間ベース（`YYYYMMDDHHMM`形式）で自動生成するように変更しました。
* この変更により、各ビルドに一意の識別子が付与され、以前の「`latest`」タグによる不明瞭なバージョニングから脱却しました。
* ビルド履歴の確認とロールバックが容易になり、より効果的なバージョン管理が可能になります。
* なし
* 新しいタグ付け方式の実装と、それがバージョン管理とCIプロセス全体に与える影響に特に注意を払っていただきたいです。
* 新しいタグ付け方式が正常に機能し、予定通りにタグが生成されるかどうかを検証する必要があります。
* また、異なるビルド間でのタグの区別と追跡が適切に行われるかを確認する必要があります。
* #18 
* [백엔드(Gin) 파이프라인 구축(バックエンドパイプラインの構築)](https://trello.com/c/rpoMvQjD/83-%EB%B0%B1%EC%97%94%EB%93%9Cgin-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8-%EA%B5%AC%EC%B6%95%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%83%91%E3%82%A4%E3%83%97%E3%83%A9%E3%82%A4%E3%83%B3%E3%81%AE%E6%A7%8 …
=> CIワークフローにおけるイメージタグの改善

.github/workflows/cd.yml, .github/workflows/ci.yml
* このPRでは、EC2インスタンスへの自動デプロイ機能の導入とCIワークフローの改善を目指しています。これにより、デプロイメントプロセスの自動化と効率化を図り、開発の生産性を向上させることが目的です。
* `cd.yml`にEC2への自動デプロイ機能を追加しました。
* `ci.yml`のワークフローを改善し、Dockerイメージのビルドにキャッシュを使用し、`latest`タグを追加しました。
* なし
* Dockerのキャッシュ利用の設定と、タグ付けの戦略について、特にご意見をいただきたいです。
* 自動デプロイのプロセスが正しく機能するかの確認。
* CIワークフローのキャッシュ利用が効率的かどうかの検証。
* #18 
* #30 
* [[AWS] - ECS로 gin 배포하기](https://velog.io/@noh0907/AWS-ECS%EB%A1%9C-gin-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)
* [Go 서버 애플리케이션을 Docker로 AWS EC2에 …
=> EC2への自動デプロイ機能とCIワークフローの改善

constants/error_messages.go, constants/http_status_codes.go
* このPRでは、エラーメッセージとHTTPステータスコードを一元管理する機能を実装しました。これにより、コードの可読性と保守性が向上します。
* `constants/error_messages.go` と `constants/http_status_codes.go` を新たに作成し、これらのファイルでエラーメッセージとHTTPステータスコードを管理するようにしました。
* なし
* 定数管理の方法について、他に効率的なアプローチがあれば提案いただきたいです。
* 特になし
* #34 
(変更点のスクリーンショットやビデオがあれば添付)
=> エラーメッセージとHTTPステータスコードの一元管理の実装

.github/workflows/ci.yml
* GitHub ActionsのDocker CIワークフローを最適化し、以前の問題を解決することを目的としています。
* キャッシュ戦略の除去により、ワークフローを簡略化しました。
* GitHub Container Registryへのイメージプッシュ方法を改善しました。
* なし
* ワークフローの最適化に関してのフィードバックを特に求めています。
* 特にありません。
* #18 
（ここにスクリーンショットやビデオを添付）
=> GitHub Actions Docker CIワークフローの最適化

main.go, migration/migration.go
* `.env` ファイルからの環境変数の読み込み問題と、データベースへの接続問題を解決したいです。
* `.env` ファイルから環境変数を正しく読み込むように `godotenv` パッケージを追加しました。
* データベースのポート番号を整数型に変換する処理を追加しました。
* なし
* 環境変数の読み込みとポート番号の扱いに関する変更部分です。
* データベース接続のテストが必要です。
* #15 
* [데이터베이스(mysql) 마이그레이션 코드 구현(データベース(mysql)マイグレーションコードの実装)](https://trello.com/c/6Pmpiaul/86-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4mysql-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98-%EC%BD%94%EB%93%9C-%EA%B5%AC%ED%98%84%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9mysql%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E5%AE%9F%E8%A3%85)
* …
=> データベース接続とマイグレーションの問題解決

.github/workflows/cd.yml
* GitHub Actionsワークフロー内で行われていたDockerイメージタグの比較ロジックを削除し、常に最新のイメージを使用してデプロイを行うようにすることで、デプロイプロセスを簡素化し、信頼性を高めたいと考えています。
* EC2へのデプロイスクリプトから、現行イメージと新しいイメージタグを比較するロジックを削除しました。これにより、GitHub Actionsは常に最新のDockerイメージをプルして、新しいコンテナを起動するようになります。
* なし
* デプロイスクリプトの変更によって、実際の動作に問題がないか特にご確認いただきたいです。
* デプロイ後のアプリケーションの動作確認が必要です。特に、新しいDockerイメージが正しくプルされ、コンテナが期待通りに起動するかを検証する必要があります。
* #30 
実際のデプロイメントプロセスのスクリーンショットやビデオがあれば、ここに添付してください。
* …
=> GitHub ActionsのDockerイメージタグ比較ロジック削除

.github/workflows/ci.yml, controllers/group_code_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/group_code_request.go, go.mod, go.sum, main.go, repositories/group_code_repository.go, services/group_code_service.go, tests/group_code_controller_test.go
* グループコード機能の実装を完了しました。これにより、ユーザーはグループコードを使用して特定のグループにアクセスできるようになります。また、Swaggerドキュメンテーションを更新し、APIエンドポイントの詳細を明確にしました。
* グループコードの作成、検証、シークレットチェック機能を追加。
* 単体テストと統合テストの追加で安定性を向上。
* Swaggerドキュメンテーションにエンドポイントの詳細を追加し、使いやすく改善。
* CI/CDパイプラインにテストステップを追加し、安定したデプロイを確保。
* 新しく追加されたテストコードの完全性。
* Swaggerのドキュメンテーションに不足や誤りがないか。
* 新しいエンドポイントの機能テスト。
* 更新されたドキュメンテーションの精度検証。
* #9 
* #39 
* [그룹 코드 기능(グループコード機能)](https://trello.com/c/3tAEHBLr/89-%EA%B7%B8%EB%A3%B9-%EC%BD%94%EB%93%9C-%EA%B8%B0%EB%8A%A5%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%82%B3%E3%83%BC%E3%83%89%E6%A9%9F%E8%83%BD)
(スクリーンショットやビデオを追加) …
=> グループコード機能の実装とドキュメンテーションの更新

migration/migration.go, models/attendance.go, models/class.go, models/class_user.go, models/group_board.go, models/group_schedule.go
このPRでは、複数のモデルファイルにおけるデータベースカラムのアノテーションを更新し、コードの明確性とデータベースとの整合性を向上させることを目的としています。主に`Attendance`, `Class`, `ClassUser`, `GroupBoard`, `GroupCode`モデルにおいて、カラムのタグを追加または修正しました。これらの変更はデータベース設計の一貫性を保ちながら、より効率的かつ明確なデータマッピングを可能にします。
* `Attendance`, `Class`, `ClassUser`, `GroupBoard`, `GroupCode` モデルにおいて、カラムのアノテーションが更新されました。
* 特定のフィールド（例：`Class`モデルの`Limitation`）にデフォルト値が追加されました。
* `GroupCode`モデルの`Secret`フィールドが、null許容型に変更されました。
* なし
* 各モデルのカラムアノテーションの更新に伴い、データベースとの整合性やマッピングの正確性を特に確認していただきたいです。
* モデルの変更によるデータベースマイグレーションの正確性を確認するためのテストが必要です。
* 更新されたアノテーションが正しく機能するかの統合テストが必要です。
* #15 
* [데이터베이스(mysql) 마이그레이션 코드 구현(データベース(mysql)マイグレーションコードの実装)](https://trello.com/c/6Pmpiaul/86-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4mysql-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98-%EC%BD%94%EB%93% …
=> モデルカラムのアノテーションを更新してコードの明確性向上

constants/error_messages.go, constants/http_status_codes.go
* このプルリクエストでは、エラーメッセージとHTTPステータスコードの構造を明確にし、コードの可読性を向上させることを目的としています。具体的には、`error_messages.go` と `http_status_codes.go` ファイル内のメッセージとステータスコードの整理と再分類を行いました。
* `error_messages.go` 内のエラーメッセージをクライアントエラー、認証エラー、サーバー＆データベースエラーのカテゴリに再分類しました。
* 新しいファイルサイズおよびファイルタイプに関するエラーメッセージを追加しました。
* `http_status_codes.go` において、クライアントエラーとサーバーエラーのHTTPステータスコードを拡張しました（例：Forbidden, Conflict, Gateway Timeout）。
* なし
* 特にありませんが、エラーカテゴリーの分類とメッセージの明確性についてご意見があればお聞かせください。
* なし
* #34 
* P2 …
=> エラーメッセージとHTTPステータスコードの構造を整理

.github/workflows/cd.yml
* GitHub Actionsのワークフローを更新して、EC2インスタンスへのデプロイを自己ホスト型ランナーを使用して行います。これにより、デプロイプロセスの制御と効率が向上し、自己ホスト型ランナーのカスタム環境を活用できるようになります。
* GitHub Actionsのワークフローが、`ubuntu-latest`から`[self-hosted, macOS, X64]`に変更され、自己ホスト型ランナーで動作するようになりました。
* DockerイメージのEC2へのデプロイが自己ホスト型ランナーを介して実行されます。
* なし
* 自己ホスト型ランナーの設定とワークフローの変更部分に特に注意してレビューをお願いします。
* 自己ホスト型ランナーを使用したデプロイが正常に動作するかどうかの検証が必要です。
* #18 
（ここにスクリーンショットやビデオ、gifを追加）
* …
=> 自己ホスト型ランナーを使用したEC2へのデプロイ機能の実装

constants/error_messages.go, controllers/class_board_controller.go, controllers/class_code_controller.go, controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_board_dto.go, dto/class_user_dto.go, models/class_board.go, models/class_code.go, models/class_schedule.go, repositories/class_user_repository.go, repositories/role_repository.go, services/class_board_service.go, services/class_user_service.go, utils/uploader.go
* クラスユーザーのロール管理機能を強化し、より効率的なユーザー管理を実現したいです。これにより、ロールに基づくアクセス制御や機能の使用が可能になります。
* `class_user_repository.go` において、ユーザーのロール更新ロジックを改善しました。
* `class_user_service.go` で、ロール名に基づくユーザーへのロール割り当て機能を追加しました。
* `role_repository.go` で、特定のロール名に基づいてロールを取得する新しいリポジトリ機能を実装しました。
* なし
* 新しいロール割り当てロジックとリポジトリの実装についてのご意見をいただきたいです。
* ロールの割り当てと更新機能に関するテストが必要です。
* #39 
* #51 
* なし
=> クラスユーザーとロール管理の機能強化

controllers/class_board_controller.go, controllers/class_schedule_controller.go, dto/class_schedule_dto.go, main.go, repositories/class_schedule_repository.go, services/class_schedule_service.go, tests/group_code_controller_test.go
* このPRでは、クラススケジュールおよびボードコントローラーの機能改善とリファクタリングを目的としています。具体的には、クラススケジュールの検索機能の追加と、クラスボードの画像アップロード処理の改善が含まれています。この変更により、ユーザーはより効率的にクラススケジュールを検索し、クラスボードの投稿時の利便性が向上します。
* クラススケジュールコントローラーに日付に基づくスケジュール検索機能を追加。
* クラスボードコントローラーでの画像アップロード処理の改善とエラーハンドリングの強化。
* コードの可読性とメンテナンス性の向上。
* なし
* 新しい検索機能の統合と画像アップロードのロジックに特に注意してください。
* エラーハンドリングとレスポンスのフォーマットについてもご確認いただきたいです。
* 新しいクラススケジュールの検索機能のテスト。
* クラスボードの画像アップロード機能のテスト。
* #42 
* #50 
（ここにスクリーンショットやビデオのリンク、またはGIFを追加）
* P3 : …
=> クラススケジュール検索機能の追加とクラスボード画像アップロード処理の改善

.github/workflows/cd.yml
* EC2インスタンス上でDockerコンテナを効率的に管理し、自動的にアップデートするプロセスを実装することがこのPRの目的です。これにより、アプリケーションのデプロイメントとメンテナンスが容易になります。関連ドキュメントは後ほどリンクを添付します。
* Dockerイメージのプル、古いコンテナの削除、新しいコンテナの実行を自動化するステップを追加しました。
* 自己ホストされたmacOSランナーでの互換性を確保しました。
* デプロイメントのステータスをチェックするためのヘルスチェックエンドポイントを追加しました。
* なし
* 特に、新しいDockerコンテナ実行スクリプトの最適化とエラーハンドリングに注目していただきたいです。
* 新しいデプロイメントプロセスがEC2インスタンス上で正しく機能するかをテストする必要があります。
* #18 
(スクリーンショットやビデオをここに添付)
* …
=> EC2インスタンスへのDockerデプロイメントプロセスの自動化

.github/workflows/ci.yml
* このPRでは、GitHub Actionsのワークフローに環境変数を追加することで、CIプロセスの動的な設定とセキュリティの強化を目指しています。これにより、CIパイプラインがより柔軟かつ安全になります。
* `ci.yml`ファイルに複数の環境変数 (`MYSQL_DATABASE`, `MYSQL_USER`, `MYSQL_PASSWORD` 等) を追加しました。
* これらの変数はGitHub Secretsから取得し、ワークフローで安全に使用されます。
* なし
* 環境変数の名前や値が適切に設定されているか。
* GitHub Secretsの使用方法に問題がないか。
* GitHub Actionsが正常に実行されるかの確認。
* 環境変数が正しくワークフローに注入されているかの検証。
* #18 
GitHub Actionsの実行ログを参照してください。
=> GitHub Actionsのワークフローに環境変数を追加

.github/workflows/ci.yml, Dockerfile
* このPRでは、GitHub ActionsのワークフローとDockerfileに環境変数を統合し、CI/CDパイプラインの動的な設定とセキュリティを強化することを目指しています。
* `ci.yml`ファイルに、Dockerイメージビルドのための環境変数（データベース設定など）を追加しました。
* `Dockerfile`にARG命令を追加し、ビルド時の環境変数を取り込むようにしました。
* なし
* 環境変数の設定方法と`Dockerfile`のARG命令の使用方法に特に注意してください。
* GitHub Actionsが正常に実行されるかの確認が必要です。
* Dockerイメージが正しくビルドされ、環境変数が適切に設定されているかを検証してください。
* #18 
変更によるGitHub Actionsの実行ログやDockerイメージのビルド結果を参照してください。
=> GitHub ActionsとDockerfileに環境変数を統合

controllers/attendance_controller.go, main.go, models/attendance.go, repositories/attendance_repository.go, services/attendance_service.go
* 出席管理機能の実装とルーター設定のアップデートを通じて、システムのパフォーマンスとユーザビリティを向上させることを目的としています。特に、データモデル、コントローラ、リポジトリ、サービスの各層での変更を行い、全体的なコードの整理と最適化を図りました。
* `Attendance`モデルの構造を更新しました。
* 出席情報を管理するコントローラのロジックを実装しました。
* リポジトリのクエリを実装しました。
* サービス層での出席情報の作成と更新ロジックを実装しました。
* メインのルーター設定に出席管理のルートを統合しました。
* なし
* 出席管理機能が動作するかどうかご確認お願いします。
* はい、変更された出席管理機能全体にわたる統合テストが必要です。
* #57 
（ここにスクリーンショットやビデオのリンクを挿入）
=> 出席管理機能の実装とルーター設定

controllers/attendance_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, models/attendance.go, repositories/attendance_repository.go, services/attendance_service.go
* 出席管理システムにクラススケジュール機能を統合し、より効率的な出席追跡と管理を可能にします。この更新により、各クラスのスケジュールに基づいて出席を管理し、ユーザーが特定のクラススケジュールに対して出席状況を確認できるようになります。
* `Attendance`モデルに`ClassScheduleID`を追加しました。
* 出席情報の取得、更新、削除に関するロジックをクラススケジュール機能に対応させました。
* 出席情報を記録する際に、特定のクラススケジュールIDに紐づけるようにしました。
* なし
* 新しく追加されたクラススケジュールIDの統合方法と、それが出席情報の取得に与える影響に特に注意していただければと思います。
* クラススケジュールIDが正しく出席情報と紐づいているかの検証。
* 新しい出席情報の登録と既存の出席情報の更新が正しく行われるかのテスト。
* #57 
* [관리자(管理者) - 출석(出席)](https://trello.com/c/tLG3mAak/92-%EA%B4%80%EB%A6%AC%EC%9E%90%E7%AE%A1%E7%90%86%E8%80%85-%EC%B6%9C%EC%84%9D%E5%87%BA%E5%B8%AD)
なし
* P1 : 必ず反映してください (Request …
=> 出席管理システムにクラススケジュール機能を統合するための改善

.github/workflows/ci.yml, Dockerfile, main.go
* Docker環境でのアプリケーションのデプロイと運用を改善するため、環境設定のロジックとDockerfileの更新を行いました。この変更により、本番環境でのセットアップとデバッグモードの管理が容易になります。
* `main.go`での環境変数のロード方法を改善し、`.env`ファイルの有無に基づいて環境変数を読み込むように変更しました。
* Dockerfileを更新し、マルチステージビルドを実施してイメージサイズを最適化しました。
* CIの設定ファイルを更新し、Dockerイメージのビルドとプッシュプロセスを改善しました。
* なし
* 環境変数のロードロジックとDockerfileの設定に特に注意していただきたいです。また、CIの設定についても見ていただけると幸いです。
* ローカル環境とDocker環境でのアプリケーションの動作確認が必要です。また、CIプロセスでのビルドとデプロイが正常に動作するかも確認が必要です。
* #18 
スクリーンショットやビデオなどの作業中の記録はありませんが、ローカルおよびDocker環境でのテスト結果をレビューコメントとして追加します。
* P2 : …
=> 環境設定とDockerセットアップの改善

.github/workflows/cd.yml
* このPRでは、Amazon EC2インスタンスにおけるDockerイメージの自動デプロイプロセスの改善を目指します。特に、EC2インスタンス上の.envファイルを使用してDockerコンテナを設定する方法に焦点を当てています。
* GitHub Actionsのワークフロー (`cd.yml`) がLinux環境で実行されるように変更されました。
* Dockerコンテナの実行時に、EC2インスタンス上の`.env`ファイルが使用されるようになりました。
* なし
* `.env`ファイルの統合方法と、それがDockerコンテナの設定に与える影響に特に注意を払っていただきたいです。
* EC2インスタンスへのDockerイメージの自動デプロイに関する改善点があれば教えてください。
* EC2インスタンス上でのDockerコンテナの正常な起動と動作を確認する必要があります。
* `.env`ファイルが適切に読み込まれ、環境変数が正しく反映されているかを検証してください。
* #30 
(ここにスクリーンショットやビデオのリンク、またはGIFを挿入してください。)
* …
=> EC2への自動デプロイワークフローの更新

.github/workflows/cd.yml
* 自動デプロイが正常に動作しない問題を解決するために、GitHub Actionsワークフローを更新しました。これにより、より信頼性の高い自動デプロイメントを実現することを目指しています。
* 自己ホストされたランナーからGitHubホストのランナー(`ubuntu-latest`)に変更しました。
* AWS CLIを使用してEC2インスタンスの現在のパブリックIPアドレスを動的に取得する手順を追加しました。
* SSHを使用してEC2インスタンスにデプロイするための手順を追加しました。
* なし
* AWS CLIの設定とEC2インスタンスへのSSH接続ロジックに特に注意してください。また、セキュリティ上の懸念がないかも確認していただきたいです。
* 新しいワークフローの動作確認とEC2へのデプロイが正常に行われるかのテストが必要です。
* #30 
(作動する様子を示すスクリーンショットやビデオ、gifを追加)
* …
=> EC2自動デプロイメントのGitHub Actionsワークフローを更新

.github/workflows/cd.yml
* GitHub Actionsワークフローで発生していたAWS CLIコマンドの問題を解決することが本PRの目的です。この問題により、EC2インスタンスのIPアドレスを正確に取得できず、デプロイプロセスが停止していました。
* AWS CLIの設定コマンドを修正しました。環境変数の設定方法を変更し、コマンド構文を更新することで、EC2インスタンスのIPアドレス取得に関する問題を解決しました。
* なし
* 環境変数の設定とAWS CLIコマンドの修正部分に特に注意していただきたいです。
* デプロイプロセスを通じて、EC2インスタンスのIPアドレスが正確に取得されるかどうかを検証する必要があります。
* #30 
(スクリーンショットや動画があればここに添付)
* …
=> AWS CLIコマンドの修正によるGitHub Actionsワークフローの改善

constants/error_messages.go, controllers/attendance_controller.go, controllers/class_board_controller.go, controllers/class_code_controller.go, controllers/class_schedule_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, migration/migration.go, repositories/attendance_repository.go, repositories/class_board_repository.go, repositories/class_code_repository.go, repositories/class_schedule_repository.go, repositories/class_user_repository.go, repositories/role_repository.go, services/attendance_service.go, services/class_board_service.go, services/class_code_service.go, services/class_schedule_service.go, services/class_user_service.go
* 本PRでは、APIドキュメンテーションの改善とコード構造のリファクタリングに焦点を当てています。これにより、プロジェクトの可読性とメンテナンスの容易さが向上します。関連ドキュメントには、Swaggerのドキュメンテーションと構造変更の詳細が含まれています。
* SwaggerによるAPIドキュメンテーションを更新し、より詳細な情報を提供するようにしました。
* コードのリファクタリングを行い、可読性と効率性を向上させました。
* エラーハンドリングの改善と一貫性のあるフォーマットを実装しました。
* なし
* リファクタリングの過程で行った設計上の選択についてフィードバックをいただけると幸いです。
* リファクタリングされたコードとドキュメントの精度を確認するため、全体的なテストが必要です。
* #66 
* [리팩토링(リファクタリング)](https://trello.com/c/CkfSah0D/94-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0)
(スクリーンショットやビデオがあればここに添付)
* P1 : 必ず反映してください (Request Changes) …
=> APIドキュメンテーションとコード構造の全面的な改善

.github/workflows/cd.yml
* このPRでは、AWS EC2インスタンスへのアプリケーションのデプロイプロセスを自動化し、改善することを目的としています。これにより、デプロイの効率性が向上し、エラー率が低下します。
* EC2インスタンスのIPアドレス取得プロセスを削除し、固定されたElastic IPを利用するように変更しました。
* GitHub Actionsを使用して、DockerイメージのCIワークフローからEC2インスタンスへのデプロイプロセスを自動化しました。
* なし
* 自動化スクリプトのロジックと、Elastic IPの設定に特に注意してレビューをお願いします。
* GitHub Actionsによる自動デプロイの動作確認。
* EC2インスタンスへのアクセスとアプリケーションの動作検証。
* #30 
(変更点を理解するのに役立つスクリーンショットやビデオ、またはgifをここに添付する)
=> AWS EC2インスタンスのデプロイ自動化の改善

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go
* ClassUserControllerに`ChangeUserRole`メソッドを追加し、`main.go`に新しいルートとコントローラの初期化を組み込みました。また、Swaggerドキュメントを更新して、新しいAPIエンドポイントを反映させました。
* `ClassUserController`に新しい機能が追加され、APIの利用者がユーザーのロールを更新できるようになりました。さらに、Swaggerドキュメントも更新され、APIの最新の状態を正確に表現しています。
* なし
* 新しく追加された`ChangeUserRole`メソッドのロジックとエラーハンドリングに注目していただきたいです。
* 新しい機能の動作確認と、Swaggerドキュメントでの新しいエンドポイントの表現が適切であるかの確認が必要です。
* #72 
* [관리자(管理者) - 그룹 멤버 관리(グループメンバー管理)](https://trello.com/c/VkHNH87S/62-%EA%B4%80%EB%A6%AC%EC%9E%90%E7%AE%A1%E7%90%86%E8%80%85-%EA%B7%B8%EB%A3%B9-%EB%A9%A4%EB%B2%84-%EA%B4%80%EB%A6%AC%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E7%AE%A1%E7%90%86)
(スクリーンショットやビデオの添付)
* …
=> ClassUserControllerの機能拡張とSwaggerドキュメントの更新

main.go
* このPRは、ローカル開発環境における環境変数の読み込み問題を解決することを目的としています。具体的には、`.env`ファイルから環境変数を自動的に読み込む機能を追加しました。
* `godotenv`ライブラリをプロジェクトに追加し、`main.go`にて環境変数を読み込むロジックを実装しました。これにより、開発者は手動で環境変数を設定する手間が省かれ、ローカル開発がよりスムーズになります。
* なし
* 新たに追加された環境変数の読み込みロジックの効率性や、`godotenv`ライブラリの実装方法について意見があればお願いします。
* `.env`ファイルから環境変数が正しく読み込まれるかどうかのテストが必要です。
* #75 
* なし
=> ローカル開発環境用の環境変数読み込み機能追加

controllers/attendance_controller.go, controllers/class_board_controller.go, controllers/class_schedule_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, middlewares/authentication_middleware.go, repositories/class_user_repository.go, services/class_user_service.go
* このプルリクエストは、APIのミドルウェア機能を統合し、対応するドキュメントを更新することを目的としています。主に、認証とアクセス制御の改善、APIのセキュリティ強化、およびSwaggerドキュメントの正確性向上に貢献します。
* 認証とアクセス制御のための新しいミドルウェアを追加しました。
* 既存APIのセキュリティを強化しました。
* Swaggerドキュメント(`docs/docs.go`)を最新のAPI仕様に合わせて更新しました。
* なし
* ミドルウェアのセキュリティ設定とドキュメントの記述に関して、特に注意深くレビューしていただければ幸いです。
* 新しいミドルウェアが正しく機能するかのテスト。
* Swaggerドキュメントの精度と完全性の検証。
* #78 
* [관리자(管理者) - 그룹 멤버 관리(グループメンバー管理)](https://trello.com/c/VkHNH87S/62-%EA%B4%80%EB%A6%AC%EC%9E%90%E7%AE%A1%E7%90%86%E8%80%85-%EA%B7%B8%EB%A3%B9-%EB%A9%A4%EB%B2%84-%EA%B4%80%EB%A6%AC%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E7%AE%A1%E7%90%86)
(ここにスクリーンショットや動画を追加)
* …
=> ミドルウェアの統合とドキュメント更新

services/class_code_service.go
* このPRでは、`CheckSecretExists`メソッド内で`*string`タイプの`Secret`フィールドを適切に扱う方法を改善します。具体的には、フィールドが`nil`でないかつ空文字列でないことを確認することで、より正確な検証を行うことができます。
* `classCode.Secret`が`nil`または空文字列でないことを確認するロジックを`CheckSecretExists`メソッドに追加しました。
* なし
* 追加されたnilと空文字列のチェックロジックについてご意見をいただきたいです。
* `CheckSecretExists`メソッドの動作確認と、新しいロジックが意図した通りに機能しているかをテストしてください。
* #39 
* [그룹 코드 기능(グループコード機能)](https://trello.com/c/3tAEHBLr/89-%EA%B7%B8%EB%A3%B9-%EC%BD%94%EB%93%9C-%EA%B8%B0%EB%8A%A5%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%82%B3%E3%83%BC%E3%83%89%E6%A9%9F%E8%83%BD)
* P1 : 必ず反映してください (Request Changes) - …
=> CheckSecretExistsメソッドのnilと空文字列チェックの改善

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
- クラス内でユーザーが自身のニックネームを変更できる機能のAPIを実装しました。これにより、ユーザーは
自分のニックネームを更新することができ、ユーザーエクスペリエンスが向上します。この変更は、ユーザーの満足度向上に直結するものです。
- ニックネームを変更するためのAPIエンドポイントを新たに設計しました。
- データベースを更新するロジックを実装し、ニックネームの変更が即時に反映されるようにしました。
なし
- ニックネーム変更機能のAPIエンドポイントの設計とデータベース更新ロジックについて、特にセキュリティ面や効率性に問題がないか確認いただきたいです。
- ニックネーム変更後のデータベースの整合性確認
- 異なるニックネームでの更新テスト
- #86 
- [일반 유저(一般ユーザー) - 그룹(グループ)](https://trello.com/c/lhme6nMf/79-%EC%9D%BC%EB%B0%98-%EC%9C%A0%EC%A0%80%E4%B8%80%E8%88%AC%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC-%EA%B7%B8%EB%A3%B9%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97)
(変更後の機能が動作する様子を示すスクリーンショットやビデオ、gifをここに追加)
* コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することができ …
=> クラス内でニックネーム変更APIの実装

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_dto.go, main.go, repositories/class_repository.go, services/class_service.go
新しいクラス作成APIの実装が完了しました。これにより、ユーザーはクラス名、最大人数、クラスの説明、クラスの代表写真を入力し、新しいクラスを作成できるようになります。この機能は、プラットフォームの多様性とユーザー満足度を向上させ、より多くのユーザーの参加を促します。
- 新しいクラス作成APIエンドポイントの設計と実装
- クラス名、最大人数、クラスの説明、クラスの代表写真を入力するためのリクエストデータ構造の定義
- 入力されたデータをデータベースに保存するロジックの実装
これらの変更により、ユーザーは簡単に新しいクラスを作成し、プラットフォームに登録できるようになります。
なし
特にデータベースに保存するロジックの実装部分について、効率性とセキュリティの観点からレビューをお願いしたいです。また、APIエンドポイントの設計に関してもご意見をいただけると幸いです。
- 新しいクラス作成APIの動作確認
- リクエストデータ構造が正しく定義されているかの検証
- データベースに保存するロジックのテスト
* #88 
この段階では、具体的なスクリーンショットやビデオ、gifはありません。APIの動作テスト後に、実際のリクエストとレスポンスの例を追加予定です。
* P1 : 必ず反映してください (Request Changes) - …
=> クラス作成機能の実装

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_user_dto.go, main.go, repositories/class_user_repository.go, services/class_user_service.go
* 特定のユーザーがどのクラスに登録されているかを確認できるAPIの実装を完了しました。このAPIは、ユーザーが参加しているクラスのリストを取得することを目的としています。開発の背景には、ユーザー管理システムの効率化と利便性の向上があります。関連ドキュメントやダイアグラムは現在のところ特にありませんが、必要に応じて追加情報を提供することができます。
* このAPIにより、フロントエンドから簡単に特定のユーザーがどのクラスに参加しているかを確認できるようになりました。これにより、アプリケーションのユーザーエクスペリエンスが向上し、管理者はユーザーのクラス参加状況をより効率的に管理できるようになります。
* なし
* 特に、APIのレスポンス構造とエラーハンドリングの部分に注目していただきたいです。これらの実装が最適な方法で行われているか、また改善の余地があるかどうかフィードバックをいただければ幸いです。
* はい、新しく追加されたAPIのエンドポイントに対するユニットテストを追加しました。これらのテストはAPIが期待通りに動作することを保証するために重要です。テストコードに関するフィードバックも歓迎します。
* 
* #90 
* この変更により、以下のようなAPIレスポンスが得られるようになります。これは、特定のユーザーが登録しているクラスのリストを示しています。
* …
=> 特定ユーザーが登録しているクラス情報を確認できるAPIの開発

controllers/class_code_controller.go, services/class_code_service.go
* `CheckSecretExists`メソッドがクラスが存在しない場合に404エラーを返さず、falseを返していた問題を解決します。この修正により、APIの応答がより正確になり、フロントエンドでのエラーハンドリングが改善されます。
* `CheckSecretExists`メソッドがクラスが存在しない場合に適切に404エラーを返すように修正しました。
* 対応するコントローラーのエラーハンドリングを更新しました。
* なし
* 新しいエラーハンドリングのロジックに特に注意していただきたいです。
* `CheckSecretExists`メソッドの新しいエラーハンドリングに関するユニットテストを追加しました。
* #94 
* [그룹 코드 기능(グループコード機能)](https://trello.com/c/3tAEHBLr/89-%EA%B7%B8%EB%A3%B9-%EC%BD%94%EB%93%9C-%EA%B8%B0%EB%8A%A5%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%82%B3%E3%83%BC%E3%83%89%E6%A9%9F%E8%83%BD)
* P1 : …
=> `CheckSecretExists`メソッドの404エラーハンドリング修正

constants/error_messages.go, controllers/class_code_controller.go, controllers/user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, models/role.go, repositories/user_repository.go, services/class_code_service.go, services/user_service.go
* ユーザーが申請中のクラス情報を取得する機能の実装と、存在しないユーザーやクラスに対するエラーハンドリングの改善が目的です。この改善により、システムの堅牢性を高め、ユーザーエクスペリエンスを向上させます。
* ユーザーが申請中のクラス情報を取得する新しいロジックを実装。
* 存在しないユーザーのチェックと適切なエラーレスポンスの実装。
* システムの全体的なエラーハンドリングの改善。
* クラスコードコントローラーの軽微なリファクタリング。
* 新しいロジックの実装において、エラーハンドリングの方法や、システムの安定性に影響を与える可能性のある箇所です。
* 新しく追加されたロジックのユニットテストと統合テスト。
* #96 
=> ユーザー申請中クラス情報取得ロジックの実装

controllers/google_auth_controller.go
- このPRでは、ユーザーがGoogleアカウントでログインしようとする際に発生する認証エラーを修正します。最近のアップデート後にこの問題が報告され、エラーログの分析から特定のトークン検証プロセスで失敗していることが判明しました。この問題の解決は、ユーザーエクスペリエンスの向上に直結します。
-  エラーの原因となっていたトークン検証プロセスの不具合を修正しました。
- なし
- 特に、Google認証ライブラリの更新適用による影響範囲を確認していただきたいです。また、テストケースの網羅性についてもご意見をいただければと思います。
- はい、特に異なるOSやブラウザ環境でのログイン処理のテストをお願いしたいです。また、Google認証ライブラリの更新による他の機能への影響も検証が必要です。
* #99 
* [소셜 로그인](https://trello.com/c/ZiBvVL1U/40-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%E3%82%BD%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3)
- 現時点で特になし。テスト結果のスクリーンショットやビデオは、必要に応じて後ほど追加します。
* P1 …
=> Googleログインエラーの修正

main.go
* `main.go`のCORS設定に関連する問題が発生しており、それによってクロスオリジンリソース共有でエラーが発生しています。このPRは、その設定問題を解決し、外部クライアントとの互換性を改善することを目的としています。
* CORS設定を変更し、適切なHTTPヘッダーとメソッドを扱えるようにしました。これにより、外部クライアントとの通信がスムーズに行えるようになります。
* なし
* CORS設定の変更点と、それに伴うHTTPヘッダーとメソッドの処理方法です。
* CORS設定の変更後に、異なるオリジンからのリクエストが適切に処理されるかの確認が必要です。
* #101 
=> CORS設定問題の解決に関するPR

main.go
* このPRは、Next.jsローカル開発環境からのリクエストを許可するためにCORS設定を更新しました。ClassBoardのルートへのアクセス時に発生したCORS関連の問題を解決することが目的です。
* `main.go`ファイルのCORS設定を変更し、`http://localhost:3000`と`http://127.0.0.1:3000`からのリクエストを許可しました。これにより、フロントエンドとバックエンドの開発時の連携がスムーズになります。
* なし
* CORS設定の変更箇所に特に注意を払ってください。
* ローカル開発環境からのリクエストが正しく許可されているかをテストする必要があります。
* #101 
=> Next.jsローカル環境のためのCORS設定の変更

services/class_code_service.go
* このPRでは、`class_code_service`の`CheckSecretExists`メソッドで不適切なエラーコードが返される問題と、コードの重複と不整合を解決しました。具体的には、存在しないclassCodeで404エラーを適切に返すように修正し、共通のロジックをメソッド化してコードの可読性とメンテナンス性を向上させました。
* `CheckSecretExists`メソッドのエラー処理を修正し、classCodeが存在しない場合は404エラーを返すようにしました。
* 重複するロジックを`findClassCode`メソッドに抽出し、クリーンコードを実現しました。
* なし
* エラーハンドリングの部分と新しく抽出したfindClassCodeメソッドの実装に注目していただければ幸いです。
* 修正したメソッドのエラー処理が正しく機能するかのテストが必要です。
* #104 
* [클래스 비밀번호 조회 에러(クラスパスワードの照会エラー)](https://trello.com/c/34VVcDpc/99-%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EC%A1%B0%ED%9A%8C-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%91%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E3%81%AE%E7%85%A7%E4%BC%9A%E3%82%A8%E3%83%A9%E3%83%BC)
* …
=> ClassCodeServiceのエラー処理とコードリファクタリングの改善

controllers/google_auth_controller.go
- このPRでは、最近の変更でGoogle認証コールバックの実装を変更した結果、認証プロセスに問題が発生してしまったため、以前のコードに戻すことで問題を解決します。この変更により、ユーザーがスムーズにGoogleアカウントでログインできるようになります。
- Google認証コールバックの実装を以前のコードに戻しました。
- なし
- 特に、以前のコードに戻すことで生じる他の機能への影響を確認していただきたいです。また、変更を戻したことで期待通りの動作が復元されているかどうかをご確認ください。
- はい、特にGoogleアカウントでのログイン処理が以前と同様に正常に動作するかどうかを検証してください。異なるブラウザやデバイスでのテストも推奨します。
* #99 
* [소셜 로그인](https://trello.com/c/ZiBvVL1U/40-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%E3%82%BD%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3)
- 現時点で特になし。テスト結果のスクリーンショットやビデオは、必要に応じて後ほど追加します。
* P1 : 必ず反映してください (Request …
=> Google認証コールバックの実装の取り消し

controllers/google_auth_controller.go
- Google認証コールバックでクッキーを設定し、リダイレクトを追加することにより、ユーザーのログインプロセスを改善しました。この変更は、ユーザーがよりスムーズに当サイトのサービスを利用できるようにするためのものです。関連ドキュメントや、この変更を加えることになった背景については、以下のTrelloカードをご参照ください。
- Google認証のコールバック処理において、セキュリティ強化とユーザビリティ向上のためにクッキー設定とリダイレクト処理を追加しました。これにより、ユーザーがログイン後に直接アクセスしたいページへスムーズに遷移できるようになります。
- なし
- クッキーの設定方法とリダイレクト処理の実装について、セキュリティ面での懸念がないか、特に注意深く見ていただきたいです。
- 新たに追加されたクッキー設定とリダイレクト処理の動作を確認するため、複数のブラウザとデバイスでのテストが必要です。
* #99 
* [소셜 로그인](https://trello.com/c/ZiBvVL1U/40-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%E3%82%BD%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3)
変更点をわかりやすくするために、ログインプロセスの改善前後を比較したスクリーンショットやビデオをここに追加します。
* コードレビューにおいて、改善の余地がある場合は積極的にフィードバックをお願いします。
* この変更がセキュリティに与える影響について、特に注意してレビューしてください。
=> GoogleAuthControllerの修正

controllers/google_auth_controller.go
- Google認証コールバックでクッキーを設定し、リダイレクトを追加することにより、ユーザーのログインプロセスを改善しました。この変更は、ユーザーがよりスムーズに当サイトのサービスを利用できるようにするためのものです。関連ドキュメントや、この変更を加えることになった背景については、以下のTrelloカードをご参照ください。
- Google認証のコールバック処理において、セキュリティ強化とユーザビリティ向上のためにクッキー設定とリダイレクト処理を追加しました。これにより、ユーザーがログイン後に直接アクセスしたいページへスムーズに遷移できるようになります。
- なし
- クッキーの設定方法とリダイレクト処理の実装について、セキュリティ面での懸念がないか、特に注意深く見ていただきたいです。
- 新たに追加されたクッキー設定とリダイレクト処理の動作を確認するため、複数のブラウザとデバイスでのテストが必要です。
* #99 
* [소셜 로그인](https://trello.com/c/ZiBvVL1U/40-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%E3%82%BD%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3)
変更点をわかりやすくするために、ログインプロセスの改善前後を比較したスクリーンショットやビデオをここに追加します。
* コードレビューにおいて、改善の余地がある場合は積極的にフィードバックをお願いします。
* この変更がセキュリティに与える影響について、特に注意してレビューしてください。
=> Google認証コールバックの修正

controllers/class_code_controller.go, services/class_code_service.go
* クラスコードとシークレットの検証処理の誤りを修正することを目的としています。具体的には、クラスコードが見つからない場合404エラーを返すようにし、クラスコードは存在するがシークレットが間違っている場合は200レスポンスでfalseを、両方が正しい場合は200レスポンスでtrueを返すように変更します。
- `ClassCodeController` の `VerifyClassCode` メソッドのロジックを更新しました。
- `ClassCodeService` の `VerifyClassCode` メソッドをbooleanを返すように変更しました。
- 関連するユニットテストを追加し、既存のテストを修正しました。
* なし
* なし
* なし
* #111 
=> クラスコード検証ロジックの修正

controllers/class_code_controller.go
* `class_code_controller`内で発生した型変換のエラー「Cannot use 'uidUint' (type uint64) as the type uint」を解決したいです。この問題は、`uint64`型の`uidUint`を`uint`型として使用しようとしたときに生じました。
- `parseUintQueryParam`関数での`uid`の`uint64`への変換処理を修正しました。
- `VerifyClassCode`メソッド内で`uidUint`を`uint`に適切にキャストするよう変更しました。
* なし
* なし
* なし
* #111 
=> class_code_controller の型変換問題の修正

controllers/google_auth_controller.go
- GoogleAuthController内のログインコールバックメソッドを以前のコードに戻す作業を行います。最近の更新で導入された変更が期待した動作をしなかったため、以前の安定したバージョンに戻すことを目的としています。
- GoogleAuthControllerのログインコールバックメソッドを、以前のバージョンに戻しました。これにより、ログインフローが以前の安定した状態に戻ります。
- なし
- コールバックメソッドの変更による他の機能への影響がないか、特にセキュリティ関連の部分に注意してレビューしていただきたいです。
- はい、ログインプロセス全体を通じて、問題なく動作するかどうかの検証が必要です。特に、以前のコードに戻したことで新たな問題が発生していないかを確認するためのテストが必要です。
- 特になし。
- この変更による具体的なスクリーンショットやビデオは、現時点では提供できません。変更は主にバックエンドのコードに関連しており、フロントエンドの見た目に直接的な影響はありません。
* P3 : …
=> GoogleAuthControllerのログインコールバックメソッドを以前のバージョンに復旧

main.go
* CORSエラーに対処するため、Ginのルーター設定でCORSポリシーを拡大しました。これは、クライアントサイドからのリクエストに対応して、より柔軟にURLパターンをサポートするための変更です。
* `localhost:3000` と `127.0.0.1:3000` のURLに対して、末尾スラッシュがあるかないかに関わらずアクセスを許可するようにCORSポリシーを拡大しました。これにより、さまざまなURLパターンに対応できるようになり、フロントエンドとの通信がスムーズになります。
* なし
* なし
* なし
* #101 
=> CORSポリシーの設定拡大

main.go
* CORSエラーの原因を特定するために、すべてのオリジンからのリクエストを一時的に許可する設定を行いました。
* CORS設定を一時的に `*` に設定して、すべてのオリジンを許可するように変更しました。この変更はデバッグを目的としており、エラーの根本原因がCORSの設定に関係しているかどうかを判断するために使用されます。
* なし
* なし
* なし
* #101 
* P3 : …
=> CORSポリシーの一時的な全許可設定

main.go
* CORSの問題解決に向けたデバッグ作業の一環として、許可するオリジンを具体的に指定し直しました。
* 全てのオリジンを許可する設定から、`http://localhost:3000` と `http://127.0.0.1:3000` のみを許可する設定に変更しました。これにより、開発環境におけるセキュリティを向上させることができます。
* なし
* なし
* なし
* #101 
* …
=> CORSポリシーの特定オリジンへの制限

main.go
* 開発とテストを簡略化するためにCORS設定を変更しました。具体的には、`AllowOrigins` を `'*'` に設定して、どのオリジンからのリクエストも許可するようにしました。また、広範囲のオリジンアクセスポリシーに合わせて `AllowCredentials` を false に設定しました。 
- `AllowOrigins` を `'*'` に変更し、すべてのオリジンからのアクセスを許可しました。
- `AllowCredentials` を false に設定し、資格情報の使用を制限しました。
* なし
* CORS設定の変更がセキュリティに与える影響について意見をいただきたいです。
* 変更されたCORS設定が異なるオリジンからのリクエストに対応しているか確認する必要があります。
* 資格情報の設定変更が想定どおりに動作するか検証する必要があります。
* #101 
* [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%9C%E3%8 …
=> CORS設定の変更によるオリジンアクセスの拡張と資格情報設定の更新

main.go
* このPRでは、CORS設定を以前のより制限的な状態に戻し、セキュリティを強化することを目指しています。以前はすべてのオリジンからのアクセスを許可していましたが、これを `http://localhost:3000` に限定しています。
- CORSの `AllowOrigins` を `http://localhost:3000` のみに限定しました。
- `AllowCredentials` を true に設定し、特定のオリジンに対して資格情報の使用を許可しました。
* なし
* 変更したCORS設定がセキュリティに与える影響について、特に検討していただきたいです。
- `http://localhost:3000` からのリクエストが正常に動作するかの検証が必要です。
- 資格情報の承認が正しく機能しているかを確認する必要があります。
* #101 
* [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%9C%E3%83%BC%E3%83%89 …
=> CORS設定の再制限と資格情報ポリシーの更新

main.go
* このPRでは、アプリケーションのCORS設定をより柔軟に対応できるように、動的なオリジン許可のロジックを導入しました。これにより、事前に定義された複数のオリジンからのリクエストを適切に処理できるようになります。
- `setupRouter`関数内でCORSミドルウェアをカスタマイズし、リクエストの`Origin`ヘッダーに基づいて`Access-Control-Allow-Origin`を動的に設定しました。
- 定義済みの許可されたオリジンリストを使用し、リクエストのオリジンが一致する場合に適切なヘッダーを設定します。
* なし
* 動的CORS設定のロジックについて、特にセキュリティ面での考慮点があれば、ご意見をいただきたいです。
- 複数の異なるオリジンからのリクエストが適切に処理されるかどうかの検証が必要です。
- 新しいCORS設定がアプリケーションの他の機能に影響を与えないことを確認する必要があります。
* #101 
* [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83 …
=> CORS設定の動的対応に関する改善

main.go
* 開発とテスト環境でのアクセスを容易にするために、CORS設定を単純化しました。この変更により、すべてのオリジンからのリクエストを許可するようにCORSポリシーを更新しました。
- CORS設定を動的なものから静的なワイルドカード（'*'）ベースの設定に変更しました。
- すべてのオリジンを許可することで、開発とテストがよりスムーズになります。
- OPTIONSリクエストに対して204ステータスで即時応答するように、プリフライト処理を改善しました。
* なし
* 静的なCORS設定への変更が、セキュリティ面での影響を考慮して適切かどうかのフィードバックをいただきたいです。
- CORS設定の変更が、異なるオリジンからのアクセスにどのように影響するかを確認する必要があります。
- すべてのエンドポイントでCORS設定が適切に機能するかのテストが必要です。
* #101 
* * [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%9C%E3%83%BC% …
=> CORS設定の静的設定への変更

main.go
* APIルートのトレーリングスラッシュがCORSエラーの原因となっていました。特に開発環境でフロントエンドとバックエンドの連携がうまくいかないケースが見られました。これを解消するために、全てのAPIルートからトレーリングスラッシュを削除しました。
- すべてのAPIルート定義からトレーリングスラッシュを削除しました（`setupRoutes` 関数内）。
- `ClassBoardController`, `ClassCodeController` など、多くのAPIグループで変更を実施しました。
- APIエンドポイントのアクセシビリティと信頼性向上を期待します。
* なし
* この変更による影響範囲が広いため、特にAPIの動作確認を重点的にお願いします。また、CORSに関連する他の問題が見逃されていないかもご確認ください。
* CORSエラーに対するテストが必要です。
* #101 
* [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%9C%E3 …
=> APIルートのトレーリングスラッシュ削除によるCORS問題解決

main.go
* ローカルホスト以外からのAPIリクエスト時に発生するCORSエラーの解決
* 開発環境および他の環境からのAPIアクセスを可能にするためのCORSポリシーの改善
* `Access-Control-Allow-Origin` ヘッダーを `"*"` に設定して、すべてのオリジンからのリクエストを許可
* フロントエンドとのAPI通信がスムーズに行えるようになりました
* なし
* 新しいCORS設定によるセキュリティリスクや潜在的な問題がないかどうか
* 新しいCORS設定によるセキュリティリスクや潜在的な問題がないかどうか
* #101 
* …
=> CORSポリシーの改善によるアクセス制御エラーの解決

dto/class_user_dto.go, repositories/class_user_repository.go
- GetUserClasses関数において、特定のユーザーがどの役割(role_id)でクラスに参加しているかを明確にするため、Selectメソッドの引数に`class_users.role_id`を追加しました。これにより、APIの応答からユーザーの役割を直接確認できるようになります。
- GetUserClasses関数のSelectメソッドの引数に`class_users.role_id`を追加しました。
- これにより、返されるクラス情報にユーザーの役割IDが含まれるようになりました。
- なし
- 新しく追加した`class_users.role_id`のデータが正しく反映されているか、特にデータベースとの連携部分を確認していただきたいです。
- はい、変更後の関数が期待通りにユーザーの役割IDを含むクラス情報を正確に返すか、実際のデータを用いてテストする必要があります。
- #124 
- この変更による具体的な出力結果の変化を示すスクリーンショットやビデオは、必要に応じて後ほど追加します。
* P3 : …
=> GetUserClasses関数のSelectメソッド引数にclass_users.role_idを追加

controllers/google_auth_controller.go
- ユーザーがログインを完了した後、自動的にメインページへリダイレクトされる機能が欠けていたため、ユーザーエクスペリエンスが低下していました。このPRでは、ログイン成功後にユーザーをメインページに自動的にリダイレクトする機能を実装し、利便性を向上させます。
- ログイン成功後のリダイレクト処理を実装しました。これにより、ユーザーはログイン後にすぐにメインページにアクセスできるようになります。
- なし
- リダイレクト処理の実装方法について、特にセキュリティ面やユーザビリティの観点で問題がないかどうかを確認していただきたいです。
- 異なるブラウザやデバイスでのログイン後のリダイレクト処理の動作確認が必要です。
- #126  
- ログイン後のリダイレクト処理の動作を示すスクリーンショットやビデオ、gifを追加予定です。
=> ログイン後のメインページへのリダイレクト機能を追加

main.go
* CORS（クロスオリジンリソースシェアリング）の設定を変更し、特定のオリジン`http://localhost:3000`からのみリクエストを許可することで、セキュリティを強化し、開発環境のリソースアクセスを制限することを目指しています。これにより、クラスボードで発生していたエラーを解決します。
* `CORS()`関数内の`Access-Control-Allow-Origin`ヘッダーの値を`"*"`から`"http://localhost:3000"`に変更しました。これにより、特定のオリジンからのみリソースアクセスが可能になります。
* なし
* セキュリティと利便性のバランスを取るために、このCORS設定の変更をどのように考えるか、フィードバックをいただきたいです。
* 変更したCORS設定によるフロントエンドとの連携テストが必要です。
* #101 
* [클래스 게시물 에러(クラスボードのエラー)](https://trello.com/c/x9LZwA5V/98-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B2%8C%EC%8B%9C%EB%AC%BC-%EC%97%90%EB%9F%AC%E3%82%AF%E3%83%A9%E3%82%B9%E3%83%9C%E3%83%BC%E3%83 …
=> CORS設定を限定的に変更してクラスボードのエラーを解決

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_user_dto.go, main.go, repositories/class_user_repository.go, services/class_user_service.go
- クラスを閲覧する際、そのクラスに参加しているユーザーの情報を確認できる機能の追加を目指します。これにより、ユーザーはクラスのメンバー構成を簡単に理解し、コミュニケーションの促進やクラスの活動計画を立てやすくなります。この機能は、プラットフォームのユーザビリティと参加者間の交流を促進することを目的としています。
- クラス情報を取得するAPIに、クラスに参加しているユーザーの情報を返す機能を追加しました。
- ユーザーの情報には、名前、プロフィール画像、役割（講師、学生など）が含まれます。
- フロントエンドでは、クラス詳細ページに参加ユーザーのリストを表示するセクションを新たに追加しました。
なし
- APIの変更によって、データベースへのクエリが増加し、パフォーマンスに影響を及ぼす可能性があります。特に、クラスに多数のユーザーが参加している場合のデータ取得の効率化について、ご意見や提案があればお聞かせください。
- 新しいAPI機能の動作確認
- 大規模なクラスでのパフォーマンステスト
- フロントエンドの表示が適切に行われるかの確認
- #130 
この段階では、具体的なスクリーンショットやビデオ、gifはまだ用意されていません。フロントエンドの実装が完了次第、実際の画面表示例を追加予定です。
* P1 : 必ず反映してください …
=> クラス内ユーザー情報確認機能の追加

controllers/class_board_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, repositories/class_board_repository.go, services/class_board_service.go
* #133 
* クラス掲示板のリスト表示にページネーション機能を追加し、データの大量表示問題を解決することがこのPRの目的です。この機能により、ユーザーは掲示板のデータを効率的に閲覧できるようになります。
* `class_board_service`にページネーション機能を追加しました。
* `class_board_controller`の`GetAllClassBoards`メソッドを更新して、ページネーションパラメーターを扱えるようにしました。
* Swaggerドキュメントを更新して、新しいページネーションパラメーターを反映しました。
* なし
* ページネーションのロジックとエラーハンドリングの部分です。特に、無効なページ番号やページサイズのリクエストを適切に処理しているかを確認していただきたいです。
* ページネーションの動作確認。
* 異なるページ番号やページサイズでの適切なデータ応答を検証。
* #42 
* #133 
* [클래스 게시판 페이지네이션 기능 필요(クラス掲示板ページネーション機能が必要)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-236)
* P1 : 必ず反映してください …
=> クラス掲示板にページネーション機能の追加

constants/error_messages.go, constants/http_status_codes.go, controllers/chat_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/chat_service.go
* #81 
* チャット機能を統合し、そのプロセスに関連するエラーメッセージの追加とSwaggerドキュメントの更新を行いました。これにより、ユーザー間のコミュニケーションを円滑にし、開発者がAPIの使用方法をより簡単に理解できるようになります。
- チャットルームのハンドリングとメッセージングエンドポイントの実装。
- 新しいエラーメッセージを`constants/error_messages.go`に追加。
- チャットAPIのエンドポイントに関するSwaggerドキュメントを更新。
* なし
- チャット機能の実装ロジックとその影響範囲。
- 追加されたエラーメッセージの適切性と明確さ。
- チャット機能の動作テスト。
- APIのレスポンスとドキュメントの整合性確認。
* #81 
* P2 : …
=> チャット機能の統合とドキュメント更新

controllers/google_auth_controller.go
- 最近のブラウザのセキュリティポリシー強化に伴い、クッキーのSameSite属性の設定を追加する必要が生じました。この変更は、クロスサイトリクエストフォージェリ（CSRF）攻撃を防ぐために不可欠です。このPRでは、当社のウェブアプリケーションが最新のブラウザセキュリティ要件を満たすように、クッキーの処理方法を更新します。
- クッキーのSameSite属性に「Strict」または「Lax」を設定し、ブラウザが第三者のサイトからのリクエストを受け付ける方法を制限しました。これにより、ユーザーのセッション情報が意図しない形で外部に漏れるリスクを低減しました。
- なし
- SameSite属性の設定値（「Strict」または「Lax」）について、適切な選択をしたかどうかの確認をお願いします。また、特定のサービスにおいて予期せぬ挙動が発生しないか、特に注意してレビューしていただけると幸いです。
- 各ブラウザ（Chrome、Firefox、Safariなど）でウェブアプリケーションが正常に動作するかの確認が必要です。特に、ログインセッションが正常に維持されるかどうかを重点的にテストしてください。
- #99
- この変更による直接的なUIの変更はありませんが、開発者ツールのコンソールやネットワークタブで、クッキーのSameSite属性が正しく設定されていることを確認できます。
* …
=> SameSite クッキー設定の追加

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/class_user_service.go
* #139
* ユーザーがお気に入りに追加したクラスを確認できる新しい機能を実装し、この機能のSwaggerドキュメントを更新することを目指しています。ユーザーのお気に入りクラス情報を効率的に管理し、ユーザーエクスペリエンスを向上させるために必要です。
* お気に入りのクラスを取得する新しいエンドポイントが追加されました。また、この機能に関するSwaggerドキュメントも更新され、APIの使用方法がより明確になりました。
* なし
* 新しいエンドポイントの実装方法とSwagger文書の説明が十分に明確かどうか、レビューをお願いします。
* 新しいエンドポイントに関する単体テストが必要です。
* #139
* …
=> お気に入りクラス機能の実装とSwagger文書の更新

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* このPRでは、特定のユーザーに対応するクラスを効率的に取得する新しい機能`GetUserSpecificClasses`の実装を目指しています。この機能はユーザーが持つ特定の役割に基づいてクラス情報を取得するために重要です。
* #141 
* このPRでは、サービス層、コントローラー層、リポジトリ層において、ユーザー特有のクラスを取得するためのメソッドを追加しました。また、この機能をサポートするためのAPIルーティングとSwaggerドキュメントも更新しました。
* なし
* 特に、新しく追加されたメソッドのロジックとAPIのルーティング設定にご注目いただければ幸いです。
* この機能に関連するAPIエンドポイントについては、適切なレスポンスが返るかどうかの確認が必要です。
* #141 
* …
=> 特定ユーザークラス取得機能の実装

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* ユーザーの役割（管理者、申請者、招待者）に基づいて、適切なクラス情報を取得する新機能の実装。
* #143 
* ユーザーの役割（管理者、申請者、招待者）によってクラス情報をフィルタリングして取得するロジックの導入。
* なし
* フィルタリングロジックの効率性と役割に基づくデータアクセスの制限に特に注意してください。
* 新しいフィルタリングロジックの包括的なテストが必要です。
* #143 
* P2 : …
=> ユーザーの役割に基づくクラス情報取得機能の追加

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
* このPRでは、`GetUserClassesByRole`関数のエラーハンドリングを改善しました。具体的には、無効なリクエスト、クラスが見つからない場合、および内部サーバーエラーが発生した際の処理を追加しました。これにより、より堅牢なバックエンドロジックと明確なエラーレスポンスを提供できます。
* #143 
`class_user_controller.go`内の`GetUserClassesByRole`関数において、以下のエラーケースのハンドリングを追加しました：
* ユーザーIDやロールIDが無効な場合に400エラーを返します。
* クラスが見つからない場合に404エラーを返します。
* 内部サーバーエラーが発生した場合に500エラーを返します。
* なし
* エラーハンドリングの実装方法とそれに伴うレスポンスメッセージの適切性についてご確認いただければと思います。
* 新たに追加されたエラーケースの動作確認と、既存機能への影響をテストする必要があります。
* #143 
* …
=> ユーザーのロールに基づくクラス情報取得のエラーハンドリングを改善

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* このPRでは、特定のユーザーIDとクラスIDを基にしたクラスユーザー情報の取得機能の実装と、Swagger文書の更新を行います。これにより、ユーザーとクラス間の関係性をより詳細に把握できるようになります。
* #146 
* `class_user_controller`に新しいエンドポイント `/cu/{uid}/{cid}/info` の追加。
* Swagger文書の更新。
* なし
* 新しいエンドポイントの実装方法とSwagger文書の記述方法に注目していただければ幸いです。
- 新しいエンドポイントの動作テスト。
- Swagger文書の正確性の確認。
* #146 
* コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することがで …
=> ユーザーとクラスに関連する情報の取得機能とSwagger文書の更新

controllers/google_auth_controller.go
- 本PRでは、ローカル開発環境でのセキュリティ設定の調整を目的としています。具体的には、ローカル環境でHTTPSを使用せずに開発を行う際に、セキュアなCookie設定が障害となるため、Secure属性をfalseに設定する変更を行いました。これにより、ローカルでの開発がよりスムーズに行えるようになります。
- CookieのSecure属性をローカル開発環境ではfalseに設定することにより、HTTPSを必要としない開発環境でもセッション管理を正常に行えるようになりました。
- なし
- この変更がセキュリティに与える影響を最小限に抑えつつ、ローカル開発の利便性を向上させるための最適な方法かどうか、特に設定の適用範囲についてご意見をいただければと思います。
- ローカル環境と本番環境の両方でCookieの挙動が期待通りであるかの確認が必要です。特にローカル環境でのセッション管理が正常に機能すること、本番環境でSecure属性がtrueに戻っていることを確認してください。
- #99 
- この変更による具体的なスクリーンショットやビデオはありませんが、ローカル開発環境でのセッション管理が正常に行えることを確認してください。 …
=> クッキー設定のためSecure属性を変更

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, models/role.go, repositories/class_user_repository.go, services/class_user_service.go
* クラスメンバー取得ロジックの改善
* Roleモデルの拡張
* #152 
* クラスメンバー取得のロジックを改善しました。
* Roleモデルに新しいENUM値を追加しました。
* なし
* 特になし
* クラスメンバー取得ロジックの単体テスト
* #152 
=> クラスメンバーのロジック改善とRoleモデル更新

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_repository.go, services/class_service.go
* クラス情報取得機能を実装し、Swaggerドキュメンテーションを更新して、APIの使用を容易にすることがこのPRの主な目的です。
* #154 
* クラス情報を取得するためのエンドポイント `/cl/{cid}` の実装。
* Swaggerドキュメンテーションにこれらの新しいエンドポイントの詳細を追加。
* なし
* 特に新しいエンドポイントの実装に関するコードレビューをお願いしたいです。また、Swaggerのドキュメンテーションについてのフィードバックも歓迎します。
* 新しいエンドポイントの動作確認。
* Swaggerドキュメンテーションが正確かどうかの確認。
* #154 
* …
=> クラス情報取得APIの実装とSwaggerドキュメンテーションの更新

constants/error_messages.go, controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* このPRは、`ToggleFavorite` 機能を新規に実装し、ユーザーがクラスをお気に入りとしてマークしやすくすることを目的としています。この機能はユーザーエクスペリエンスを向上させ、よく使用するクラスへのアクセスを容易にします。
* #156 
* 新規に `ToggleFavorite` 機能を追加しました。これにより、ユーザーは特定のクラスをお気に入りに追加または削除することができます。
* なし
* 新たに追加された `ToggleFavorite` の処理ロジックとエラーハンドリングに注目していただきたいです。
* `ToggleFavorite` の動作確認が必要です。特に、ユーザーとクラスの組み合わせが存在しない場合のエラーハンドリングを確認してください。
* #156  …
=> ToggleFavorite 機能の実装

controllers/google_auth_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go
- Google認証の流れを改善し、よりセキュアで効率的なユーザー認証を実現することを目指しました。具体的には、`GoogleAuthController`の`GoogleAuthCallback`メソッドを`ProcessAuthCode`に変更し、認証コードをリクエストボディから直接読み取るようにしました。また、この変更を通じて、新しいユーザーを作成または既存のユーザーを更新し、認証トークンを生成する機能を追加しました。
- `GoogleAuthController`内のメソッド名を`GoogleAuthCallback`から`ProcessAuthCode`に変更しました。
- 認証コードをリクエストボディから読み取るように修正しました。
- 読み取った認証コードを用いてユーザー情報を取得し、新規ユーザーの作成または既存ユーザーの更新、トークンの生成を行う機能を追加しました。
なし
新たに追加されたユーザー情報の取得とトークン生成のロジックについて、セキュリティ面での懸念がないか確認していただきたいです。
- 新規ユーザー作成と既存ユーザー更新の処理が正しく機能するかの確認
- 生成されたトークンが適切に機能するかのテスト
- #99 
変更後の認証フローの動作確認のためのスクリーンショットやビデオは、このPRには直接添付されていませんが、必要に応じて提供可能です。
- この変更によりユーザー認証のフローが変更されるため、関連するドキュメントやユーザーガイドも更新する必要があります。
- セキュリティレビューを特に重視し、外部からの不正アクセスやデータの漏洩がないように細心の注意を払ってください。
=> GoogleAuthCallbackメソッドの変更

controllers/class_code_controller.go, controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/role_repository.go, services/class_user_service.go
* このPRでは、ユーザーロールの割り当て方法を改善し、ロール名に基づく割り当てシステムを導入しています。これにより、ロール管理がより直感的で保守しやすくなります。
* #159 
* `class_user_service`の`AssignRole`メソッドを改善し、ロール名に基づくユーザーのロール割り当てを可能にしました。また、`class_user_controller`の`ChangeUserRole`関数も更新し、ロール名でのリクエストを受け入れるように変更しました。
* なし
* 新しいロール割り当てロジックの実装と、それに伴う関数の変更点に注目していただきたいです。
* 新しいロール割り当て方法のテストが必要です。適切なロール名が正常に割り当てられることを確認してください。
* #159 
* …
=> ユーザーロール管理機能の改善

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* このPRでは、ユーザーをクラスから削除する機能を実装し、Swaggerドキュメントを更新しました。これにより、システム管理者が必要に応じてユーザーをクラスから削除できるようになります。
* #161 
- `class_user_controller` にユーザーをクラスから削除する新しいエンドポイントを追加しました。
- `class_user_service` に削除ロジックを実装しました。
- `class_user_repository` を更新して、データベースからユーザー情報を削除する処理をサポートしました。
- Swaggerドキュメントを新しいAPIエンドポイントで更新しました。
* なし
* 削除機能のロジックとAPIのエラーハンドリングに特に注意してください。
* 新しいエンドポイントの動作テストと既存の機能に影響がないかの確認が必要です。
* #161 
* …
=> ユーザーをクラスから削除する機能とSwaggerドキュメントの更新

main.go
- このPRの目的は、特定のAPI呼び出しでHTTPメソッドをGETからPOSTに変更することです。この変更は、データの安全性を高め、大量のデータ送信時の問題を解決するために必要です。これにより、アプリケーションのセキュリティとパフォーマンスが向上します。
- 主な変更点は、特定のエンドポイントに対するHTTPメソッドの変更です。具体的には、ユーザー情報を取得するためのAPI呼び出しをGETからPOSTに変更しました。
- なし
- HTTPメソッドの変更に伴い、関連するフロントエンドのコードも適切に更新されているか、特に注目していただきたいです。
- はい、変更後のPOSTメソッドが期待通りに動作するかを検証するために、APIのテストケースを追加しました。また、フロントエンドでの動作確認も必要です。
- #99 
- この変更によるUIの変更はありませんので、作動する様子のスクリーンショットやビデオはありません。テスト結果のスクリーンショットを追加する予定です。
=> HTTPメソッドのリクエストの変更

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, models/class_board.go, models/class_code.go, models/class_schedule.go, models/class_user.go, repositories/class_repository.go, services/class_service.go
* このPRでは、クラスを効率的に削除できる新しいDeleteClass機能を実装しました。また、データ整合性を保つために、`ClassBoard`, `ClassCode`, `ClassSchedule`のモデルを更新し、Swagger文書もこの変更に合わせて更新しました。
* #167 
* `controllers/class_controller.go`に`DeleteClass`メソッドを実装。
* `models/ClassBoard.go`, `models/ClassCode.go`, `models/ClassSchedule.go`で外部キー制約を更新。
* Swagger文書を最新のAPI仕様に合わせて更新。
* `DeleteClass`メソッドの実装方法と外部キー制約の変更についてのフィードバックを求めます。
* 新しいクラス削除機能とモデル更新のテスト。
* #167 
* …
=> クラス削除機能の実装と関連モデルの更新

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_dto.go, models/class.go, services/class_service.go
- クラスを作成する際に、どのユーザーがそのクラスを作成したかを追跡できるように、作成したユーザーのID値を保存する機能を追加する必要がありました。これは、後からクラスの管理や編集を行う際に、誰がそのクラスを作成したかを特定しやすくするためです。
- クラス作成機能に、現在ログインしているユーザーのIDをクラス情報と一緒に保存するロジックを追加しました。
- データベーススキーマを更新して、クラス情報にユーザーIDを格納するための新しいカラムを追加しました。
- クラス情報を表示する際に、作成者の情報も表示するようにフロントエンドとバックエンドの両方を更新しました。
- なし
- 新しく追加したユーザーIDの保存ロジックとデータベーススキーマの変更部分について、特に確認をお願いします。
- 新しい機能の動作確認として、クラス作成時にユーザーIDが正しく保存されるかのテストが必要です。
- #166 
- この変更による具体的なスクリーンショットや動作確認のビデオはありませんが、テスト環境での動作確認を行い、期待通りの結果が得られています。
- Reviewerはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
- Reviewerは良いコードを見つけた場合、賞賛と励ましを惜しみません。
- レビューは特別なケースでない限り、Reviewerに指定された時点から3日以内に行ってください。
- コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することができます。
* P3 …
=> クラス生成の時ユーザIDを追加

controllers/google_auth_controller.go
- ログインしたユーザー情報の中で不要な情報がフロントエンドに送信されてしまう問題を解決したいです。
- 最小限の情報だけをクライアントに送ることで、セキュリティを強化し、プライバシー保護を図りたいです。
- ユーザー情報をフロントエンドに送る際に、必要最小限の情報のみを選択して送信するように変更しました。
- 不要な個人情報の送信を防ぐことで、セキュリティリスクを低減しました。
- なし
- 変更した情報選択ロジックがセキュリティ上の問題を引き起こさないか、特に注意深くチェックしていただきたいです。
- 変更したロジックによる情報の選択と送信が正しく機能するか、ユニットテストを通して検証してください。
- #171 
- この変更によるデモは特にありませんが、必要であればテスト結果のスクリーンショットを追加します。
=> ユーザーに不要な情報の送信を制限 

docs/docs.go, docs/swagger.json, docs/swagger.yaml
* #9 
* Swagger docsエラー
* `swag init`を通じてアップデート
* なし
* `Class`タッグのAPIを見ていただけたら幸いです。
* なし
* #9 
=> Modify Swagger docs for class

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_dto.go, main.go, repositories/class_repository.go, services/class_service.go
* クラス情報の更新機能を実装しました。この機能は、クラスの情報（名前、参加制限人数、説明）を変更することができます。また、Swaggerドキュメントも更新して、APIの利用が容易になります。
* #174 
* クラス情報更新のロジックを`class_service.go`と`class_controller.go`に実装。
* Swaggerドキュメントを更新し、APIの詳細と利用方法を明確に記述。
* なし
* 更新ロジックの効率性とエラーハンドリングに特に注目していただきたいです。
* クラス情報更新時のエッジケースに対するテストが必要です。
* #174 
* …
=> クラス情報更新機能の実装とSwaggerドキュメントの更新

controllers/live_class_controller.go, go.mod, go.sum, main.go, services/live_class_service.go
* リアルタイムのオンラインクラス機能を提供するために、WebSocketプロトコルを統合しました。このPRは、リアルタイムでの双方向通信を可能にし、ユーザーの参加やアクティブな参加をよりスムーズに行うことを目的としています。
* #80 
* WebSocketを使用して、リアルタイムのクラスルーム作成と参加の機能を実装しました。
* コントローラーとサービスレイヤーにWebSocket関連のロジックを追加し、双方向通信のサポートを実現しました。
* なし
* WebSocketの統合方法と、それに伴うコントローラーとサービスの設計について意見をいただきたいです。
* 新たに追加されたリアルタイム通信機能の動作テストが必要です。
* #80 
* …
=> WebSocket統合によるリアルタイムクラス機能の実装

constants/error_messages.go, controllers/google_auth_controller.go, main.go, services/google_auth_service.go
- アクセストークンとリフレッシュトークンの有効期間を変更し、リフレッシュトークンを利用してアクセストークンを再発行するロジックを追加することです。この変更により、セキュリティを強化しつつ、ユーザーの利便性を向上させます。
- アクセストークンの有効期間を短縮し、リフレッシュトークンの有効期間を延長しました。
- リフレッシュトークンを用いてアクセストークンを再発行する新しい認証フローを実装しました。
- なし
- 新しく追加された認証フローのセキュリティに関して、特にリフレッシュトークンの管理方法についてご確認いただきたいです。
- 新しい認証フローの動作確認と、有効期間が変更されたトークンの動作テストが必要です。
- #178 
- 変更後の認証フローのスクリーンショットや動作確認のビデオを追加予定です。
=> アクセストークン再発行機能の実装

repositories/class_user_repository.go, services/class_service.go
* クラス作成機能において、クラスを作成したユーザーに自動的に管理者権限（`role_id: 2`）を付与する機能を追加することを目的としています。これにより、クラス作成者がクラスの管理をスムーズに行えるようになります。
* #166 
* [관리자(管理者) - 클래스 생성(クラス作成)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-246)
* クラス作成時にクラス作成者に管理者権限を付与するロジックを`class_service`に追加しました。`class_user_repository`の`Save`メソッドを使用して、クラス作成者の情報と権限をデータベースに保存しています。
* なし
* 追加された機能の実装ロジックと、データベースへの影響に関してご確認いただきたいです。
* クラス作成機能と管理者権限付与の統合テストが必要です。
* #166 
* [관리자(管理者) - 클래스 생성(クラス作成)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-246)
* …
=> クラス作成時にユーザーに管理者権限を付与する機能の追加

main.go
* 実装中の機能に関連する部分を一時的にコメントアウトし、プロジェクトの安定性を確保しました。これにより、未実装の機能が原因で生じる可能性のある問題を回避し、開発プロセスをスムーズに進めることができます。
* #166 
* [관리자(管理者) - 클래스 생성(クラス作成)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-246)
* `main.go`ファイル内で、未実装の機能やコンポーネントをコメントアウトしました。これにより、これらの部分がアプリケーションの起動や実行に影響を与えることがなくなります。
* なし
* なし
* コメントアウトされたコードが現在の機能に影響を与えていないことを確認するための基本的な動作テストが必要です。
* #166 
* [관리자(管理者) - 클래스 생성(クラス作成)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-246)
* P1 : …
=> コメントアウトされた機能の一時的な削除

controllers/live_class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/live_class_service.go
* このPRは、ライブクラスの画面共有機能における管理者の認証強化とその操作性の向上を目的としています。また、APIのSwagger文書も更新し、より正確で詳細な情報を提供することを目指しています。この変更は、よりセキュアで使いやすいプラットフォームを提供することで、エンドユーザーの満足度を向上させることを目的としています。
* #80 
* `live_class_controller` と `live_class_service` において、管理者のみが画面共有を開始・停止できるようにロジックを改善しました。
* APIのSwagger文書を更新し、各エンドポイントのパラメータとレスポンスに関する説明を充実させました。
* なし
* 管理者認証のロジックが適切に実装されているかどうか、特に `live_class_service` の `isRoomAdmin` メソッドの実装に注目していただきたいです。
* 新しい認証ロジックの単体テストと、実際の画面共有機能の動作検証が必要です。
* #80 
* …
=> ライブクラスの画面共有機能の改善

controllers/live_class_controller.go
* このPRでは、`live_class_controller`内で使用されるHTTPステータスコードを生の数値からプロジェクト内で定義された定数に変更することで、コードの可読性と保守性を向上させます。これにより、将来的な変更やエラーハンドリングの一貫性が保たれ、デバッグ時の効率が向上します。
* #80 
* `http.StatusInternalServerError` とその他のステータスコードのリテラルを `constants` パッケージで定義された定数に置き換えました。
* なし
* 定数の命名とその適用範囲に特に注意を払い、適切かどうかの確認をお願いします。
* 本変更は内部的なリファクタリングのため、既存のテストを実行し、挙動が変わっていないことを確認してください。
* #80 
* …
=> ♻️ HTTPステータスコードを定数で管理するリファクタリング

controllers/google_auth_controller.go
- アクセストークンを再発行するためにリフレッシュトークンをリクエストするロジックで、リフレッシュトークンが正しく受信されていない問題を修正しました。この問題により、ユーザーはセッションの更新ができず、サービスの利用に支障をきたしていました。このPRの目的は、この問題を解決し、システムの安定性を向上させることです。
- リフレッシュトークンを受け取るロジックにおいて、リフレッシュトークンがリクエストボディまたはヘッダーに正しく含まれているかを検証する処理を追加しました。これにより、リフレッシュトークンが存在しない、または無効な場合に適切なエラーメッセージを返し、セキュリティリスクを低減します。
- なし
- リフレッシュトークンの検証処理のロジックについて、セキュリティ上の観点からも最適な方法を採用しているか、特に注目していただきたいです。
- リフレッシュトークンが正しく受信されているかどうかの単体テストと、無効なリフレッシュトークンが送られた場合の挙動を検証するテストコードを追加しました。これらのテストの結果に基づき、さらなる修正が必要かどうかをご確認ください。
- #188 
- この変更による具体的なスクリーンショットやビデオはありませんが、テスト結果をもとに、変更後の挙動が期待通りであることを確認しています。
* P1 : …
=> リフレッシュトークンを要求するロジックの修正

controllers/chat_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
* このPRでは、チャットルームのメッセージ投稿に関するバグを修正し、Swaggerドキュメントを最新のAPI仕様に更新することを目的としています。この変更により、ユーザーがスムーズにメッセージを交換できるようになります。
* #190 
* `PostToChatRoom` 関数におけるJSONのバインディング処理を修正しました。これにより、メッセージが正しく投稿できない問題を解決しました。
* Swaggerドキュメントを更新して、APIの変更点を明確にしました。
* なし
* 修正されたバインディング処理のロジックに特に注意してレビューをお願いします。また、Swaggerドキュメントの表記に不備がないかも確認していただけると助かります。
* `PostToChatRoom` 関数の動作確認
* Swaggerドキュメントの内容が実際のAPI仕様と一致しているかの検証
* #190 
* …
=> チャット機能のバグ修正とSwaggerドキュメントの更新

controllers/google_auth_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
- RefreshAccessTokenHandlerメソッドにSwaggerの注釈を追加しました。これによりAPIのドキュメンテーションが自動で更新され、開発者がAPIの仕様を容易に理解できるようになります。この変更は、APIの可視性と利用のしやすさを向上させることを目的としています。
- RefreshAccessTokenHandlerメソッドにSwaggerアノテーションを追加しました。これにより、このメソッドのAPI仕様がSwaggerドキュメントに正しく表示されるようになります。
- なし
- 追加したSwaggerアノテーションの正確さと完全性を確認していただきたいです。特に、パラメータやレスポンスの定義が正しいかどうかに注目してください。
- Swaggerドキュメントが正しく更新され、RefreshAccessTokenHandlerメソッドの仕様が正確に反映されているかどうかを確認する必要があります。
- #188 
- この変更による直接的なビジュアルの変更はありません。Swagger UIを通じてドキュメンテーションが正しく更新されているか確認してください。
- P2 : …
=> アクセストークン再発行機能のSwaggerドキュメントの更新

controllers/class_board_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go
* このPRでは、クラス掲示板の画像アップロード処理を改善し、Content-Typeが`multipart/form-data`でない場合にも処理を続けることができるようにします。また、関連するSwaggerドキュメントも更新し、APIの使用方法を明確にします。これにより、クライアント側のエラー発生率を減少させることが期待されます。
* #193 
* [클래스 게시물 수정 에러(クラス投稿修正エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-255)
- `UpdateClassBoard`関数において、Content-Typeに基づく画像アップロードの条件分岐を実装しました。
- Swaggerドキュメントを更新し、画像アップロードがオプショナルであることを明記しました。
* なし
* 新しく追加した画像アップロードの条件分岐のロジックについて、効率的な書き方があるかレビューしていただきたいです。
- 画像を含むリクエストと含まないリクエストの両方でクラス掲示板の更新が正しく行われることを確認してください。
* #193 
* [클래스 게시물 수정 에러(クラス投稿修正エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-255)
* …
=> クラス掲示板の画像アップロード処理とSwaggerドキュメントの修正

controllers/google_auth_controller.go, main.go, services/google_auth_service.go
- JWTに基づいたトークン生成と管理、リフレッシュトークンを利用したアクセストークンの再発行機能を実装しました。この機能は、セキュリティを強化し、ユーザーのセッション管理をより効果的に行うために、開発されました。
- 新たに、JWTに基づいた認証方式を採用しました。これにより、アクセストークンの有効期限が切れた場合にリフレッシュトークンを使用して、新しいアクセストークンを安全に発行することができます。
- なし
- アクセストークンとリフレッシュトークンの発行ロジックに特に注意してレビューしていただきたいです。セキュリティ上の問題がないか、十分に確認していただくことをお願いします。
- JWTの生成と検証の単体テストを追加しました。また、リフレッシュトークンを使用したアクセストークンの再発行の統合テストも行いました。
- #178 
- この機能のデモビデオやスクリーンショットは現段階では用意していませんが、必要であれば追加の説明会を実施することが可能です。
=> アクセストークン再発行機能の修正

controllers/chat_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/chat_service.go
* このPRでは、新しいチャットルーム作成機能を実装し、対応するSwaggerドキュメントを更新しました。この機能は、ユーザーがリアルタイムでコミュニケーションを取りやすくすることを目的としています。
* #197 
- チャットルームを作成するAPIエンドポイントを追加。
- チャットルームにメッセージを送信する機能を追加。
- チャットルームを削除するAPIエンドポイントを追加。
- Swaggerドキュメントにこれらのエンドポイントの詳細を反映。
* なし
* チャットメッセージの保存と取得に使用されるRedisの処理について、特に効率性とエラーハンドリングの面でのフィードバックをいただきたいです。
- チャットルーム作成のAPIレスポンス
- チャットメッセージの送信と受信のリアルタイム処理
- APIエンドポイントのドキュメントが正確に更新されているか確認
* #197 
* …
=> 新しいチャット機能とSwaggerドキュメントの更新

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, repositories/class_user_repository.go, services/class_user_service.go
* このPRはクラスリストAPIにページネーションを実装し、Swaggerドキュメントを更新することを目的としています。これによりAPIの応答性が向上し、エンドユーザーの利便性が高まります。
* #199 
* [일반 유저(一般ユーザー) - 클래스(クラス)(クラス掲示板ページネーション機能が必要)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-160)
- `GetUserClasses`、`GetFavoriteClasses`、`GetUserClassesByRole` のAPIにページネーションパラメータを追加しました。
- Swaggerドキュメントにページネーションに関する情報を明確に記載しました。
* なし
* ページネーションの実装に関して特に見ていただきたいのは、パラメータの処理方法とページ計算の正確性です。
- 新しく追加されたページネーション機能の統合テストが必要です。
- Swaggerの更新部分に関するドキュメントの正確性を確認する必要があります。
* #199 
* [일반 유저(一般ユーザー) - 클래스(クラス)(クラス掲示板ページネーション機能が必要)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-160)
* …
=> ページネーション機能とSwaggerドキュメントの更新Feat/add pagination to class listing

middlewares/authentication_middleware.go
- APIリクエストに有効なログイントークンが含まれているかどうかを確認するミドルウェアの実装を行いました。これにより、セキュリティを強化し、無効または不正なトークンを使用したリクエストを事前にフィルタリングすることができます。この変更は、APIの保護を強化し、ユーザー認証プロセスをより安全にすることを目的としています。
- 新たにログイントークン検証用のミドルウェアを導入しました。このミドルウェアは、APIリクエストのヘッダーに含まれるトークンが有効かどうかを確認し、有効でない場合はリクエストを拒否します。
- なし
- トークン検証ロジックのセキュリティ面に特に注意を払い、潜在的な脆弱性がないか確認していただきたいです。
- ミドルウェアが正しく有効なトークンのみを受け入れ、無効なトークンを持つリクエストを適切に拒否するかのテストが必要です。
- #196 
- このPRには動作の様子を示すスクリーンショットやビデオ、gifは含まれていませんが、必要に応じて提供することが可能です。
* P3 : …
=> トークンを使用して認証するミドルウェアの実装

controllers/live_class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go
* 画面共有APIが404エラーを返す問題を解決します。これはルーティングの誤設定が原因であり、特定のエンドポイントで正しいハンドラ関数が呼び出されなかったためです。
* #80 
* 画面共有のスタートとストップのAPIエンドポイントのルーティングが修正されました。
* 適切なハンドラがリクエストに応答するようになり、APIの404エラーが解消されました。
* なし
* ルーティングの変更箇所の確認と、新しいルーティングでのAPIの挙動を特にご確認いただきたいです。
* 
* #80 
* P1 : 必ず反映してください (Request Changes) - …
=> 画面共有機能のルーティングエラー修正

controllers/class_schedule_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
* 現在`PUT`メソッドで実装されているクラススケジュール更新APIを`PATCH`メソッドに変更します。これにより部分更新が適切に処理され、404エラーの問題を解消します。
* #203 
* [클래스 스케줄 수정 시 404 에러 발생(クラススケジュール修正時に404エラーが発生)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-248)
* クラススケジュール更新のエンドポイントが`PUT`から`PATCH`に変更されました。
* APIのドキュメントとSwagger仕様も更新しました。
* なし
* `PATCH`メソッドの適用によるエンドポイントの動作確認を重点的に見ていただきたいです。
* `PATCH`メソッドに変更後のAPIが正しく動作するかの統合テストが必要です。
* #203 
* [클래스 스케줄 수정 시 404 에러 발생(クラススケジュール修正時に404エラーが発生)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-248)
* …
=> クラススケジュール更新APIをPUTからPATCHに変更

main.go
- API呼び出し時にトークン認証ミドルウェアが適用されるように、ルーター設定にJWTサービスを追加することで、セキュリティの向上を図ります。この変更により、APIの使用時に有効なトークンの存在を確認できるようになります。
- ルーター設定にJWT認証ミドルウェアを追加し、API呼び出しにトークン認証プロセスを導入しました。これにより、API利用のセキュリティが強化されます。
- なし
- JWT認証ミドルウェアの適用とトークン検証ロジックに特に注意を払い、セキュリティ上の脆弱性がないか確認していただきたいです。
- JWTトークンの生成と検証ロジックの正確性、機能の安定性を確認するためのテストコードが追加されました。
- #196 
- このPRにはスクリーンショットやビデオが添付されていませんが、必要であれば提供することができます。
- Reviewerはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
- Reviewerは良いコードを見つけた場合、賞賛と励ましを惜しみません。
- レビューは特別なケースでない限り、Reviewerに指定された時点から3日以内に行ってください。
- コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することができます。
=> APIルートにおけるJWT認証ミドルウェア実装

repositories/class_user_repository.go, services/class_user_service.go
* このPRでは、ユーザーのお気に入りクラスのみを正確に取得するようにクエリを修正します。これまでの実装では、お気に入りでないクラスも取得される問題がありました。
* #206 
* `GetFavoriteClasses` 関数のSQLクエリを修正し、`is_favorite`が`true`のデータのみを取得するように変更しました。
* なし
* 修正したクエリの効率性と正確性についてご確認いただきたいです。
* 新しいクエリに基づいて、お気に入りクラスの取得が正確に行われるかの単体テストを追加しました。
* #206 
* P1 : 必ず反映してください …
=> お気に入りクラスの取得処理を修正

middlewares/authentication_middleware.go, services/google_auth_service.go
- JWTペイロード内のキー値を`user_id`から`id`へ変更することで、システム全体の一貫性を向上させ、開発および保守の効率を高めることを目的としています。この変更は、チーム内での事前の議論とシステム設計の再評価を経て決定されました。
- JWT生成ロジックで、ペイロード内の`user_id`キーを`id`に変更しました。
- JWTをパースする部分を、新しいキー`id`を認識するように修正しました。
- なし
- 新しいキー値`id`の採用によるJWTの生成とパースのロジックに特に注意を払ってレビューしていただきたいです。また、この変更が他のシステムコンポーネントに予期せぬ影響を与えないかどうかもご確認ください。
- JWTの生成とパースの単体テストを追加しました。変更が正しく機能するかを確認するために、詳細なテストケースをレビューしていただきたいです。
- #210 
- この変更による実際の動作の違いを示すスクリーンショットやビデオは特にありません。変更は主にバックエンドのロジックに関わるものであり、ユーザーインターフェイスに直接影響を与えるものではありません。
* P2 : …
=> jwtペイロードキーの変更

repositories/class_user_repository.go
* このPRでは、`GetClassUserInfo`メソッドからユーザー画像を正しく取得できない問題を解決します。この問題は、データベースとのJOINが不適切に設定されていたため発生していました。これを解決することで、APIがクラスメンバーの画像を含む情報を正確に返すようになります。
* #212 
* [클래스 유저 정보 조회 에러(クラスユーザー情報照会エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-262)
* `class_user_repository.go`ファイルの`GetClassUserInfo`関数内で、`User`テーブルとのJOINを修正しました。これにより、ユーザーの画像が正しく取得されるようになります。
* なし
* JOINの処理が適切に行われているか、特に確認していただきたいです。
* 新しいJOIN処理が導入されたため、関連するユニットテストを実施して、画像データが正常に取得できることを確認してください。
* #212 
* [클래스 유저 정보 조회 에러(クラスユーザー情報照会エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-262)
* …
=> ユーザー画像の取得問題を修正

services/google_auth_service.go
- JWTペイロードのキー値が`user_id`から`id`に変更されたため、アクセストークンを再発行するロジックにも変更が必要になりました。この変更は、システム全体の一貫性を保ち、よりシンプルな識別子を使用することで開発者が理解しやすくなることを目的としています。
- アクセストークンを生成する際のペイロードに含まれるユーザー識別子のキーが`user_id`から`id`に変更されました。これに伴い、アクセストークンを検証し、ユーザー情報を取得するロジックも更新されています。
- なし
- 新しいキー値`id`を使用してアクセストークンが正しく生成され、検証できるかどうか、特にセキュリティ面での影響がないかを重点的に確認していただきたいです。
- アクセストークンの生成と検証の単体テストが更新されています。新たに追加されたテストケースにより、変更が正しく機能することを保証する必要があります。
- #210 
- この変更による動作の違いを視覚的に示すスクリーンショットやビデオは特にありませんが、テスト結果のスクリーンショットを添付することができます。 …
=> jwtペイロードキーの変更によるアクセストークン再発行機能の修正

controllers/attendance_controller.go, controllers/chat_controller.go, controllers/class_board_controller.go, controllers/class_code_controller.go, controllers/class_controller.go, controllers/class_schedule_controller.go, controllers/class_user_controller.go, controllers/user_controller.go, main.go
* このPRでは、SwaggerにBearer Authenticationを実装してAPIのセキュリティを強化し、明確なユーザー認証プロセスを確立することを目的としています。Bearer認証はAPI利用の際にセキュリティを向上させるため、必要不可欠です。
* #215 
* Swagger設定にBearer Authenticationのオプションを追加しました。これにより、APIへのアクセスには適切な認証トークンが必要となります。
* なし
* 認証スキームの統合部分のコードを特に注意深く見ていただきたいです。セキュリティへの影響を考慮して、適切な実装がなされているか確認をお願いします。
* 新たに追加された認証機能のテストコードも一緒にレビューしていただけると幸いです。
#215 
=> SwaggerにBearer Authenticationを実装

controllers/live_class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/live_class_service.go
* WebSocketを通じた画面共有機能の実装を行いました。これにより、リアルタイムでの画面共有がスムーズかつ信頼性高く行えるようになります。この変更は、ライブセッション中のパフォーマンスを向上させることを目的としています。
* #80 
* WebSocketの導入とWebRTC設定のリファクタリングを通じて、クライアント間の画面共有機能を強化しました。これにより、接続の安定性とデータの伝送効率が向上しています。
* なし
* WebSocketとWebRTCの統合部分のコードを中心にレビューしていただきたいです。特にセッション管理とエラーハンドリングの部分が懸念事項です。
* 新しい画面共有機能に関する統合テストとエンドツーエンドのテストを追加しました。これらのテストの適切な実行とカバレッジの確認が必要です。
* #80 
* …
=> [MIN-145] 管理者の画面共有機能の強化

main.go
* このPRでは、画面共有機能の信頼性とパフォーマンスを向上させるためのWebRTC設定の強化を目指しています。具体的には、セッション記述の取り扱いやピア接続の設定方法に関する改善を行いました。この変更により、リアルタイムでの画面共有がよりスムーズに行えるようになることを期待しています。
* #80 
* WebRTCのピアコネクション設定におけるインターセプターの登録方法を改善し、ビデオデータの扱いを最適化しました。
* セッション記述プロトコル(SDP)のデコード及びエンコード処理の強化を行い、通信の安定性を高めました。
* なし
* 新しく追加したインターセプターの設定方法について、他の設定との統合性に問題がないか確認していただきたいです。
* 新設定が実際の画面共有セッションにおいて期待通りのパフォーマンスを発揮するかの確認が必要です。
* 異なるネットワーク条件下での安定性テストを行うことを推奨します。
* #80 
* …
=> [MIN-145] 画面共有機能のWebRTC設定を強化

controllers/live_class_controller.go, services/live_class_service.go
* このPRでは、画面共有機能のプロセスをシンプルにし、ストリーミングサービスとの統合を強化することを目的としています。具体的には、クラスIDを用いて直接画面共有情報を取得するように変更し、新たに実装したストリーミングセッション開始機能を通じてストリーミングのURLを生成するプロセスを確立しました。
* #80 
- `GetScreenShareInfo` 関数をユーザーIDのパラメータからクラスIDのみを使用する形に変更し、処理を効率化。
- `StartStreamingSession` 関数を追加し、ストリーミングURLの生成をAPI呼び出しによって行うようにしました。
- `SaveScreenShareInfo` 関数を最適化し、エラーハンドリングとデータの整合性を向上させました。
* なし
* 新しいストリーミングセッション開始処理とそのエラーハンドリングに注目していただきたいです。特にAPIからの応答が不正な場合のエラー処理の部分です。
- 新しく追加されたAPI呼び出しのテストが必要です。
- ストリーミングURL生成と情報保存の統合テストを行うこと。
* #80 
* …
=> [MIN-145] 画面共有機能の最適化とストリーミングプロセスの統合

main.go
* このPRでは、WebSocket通信とWebRTCの統合プロセスを改善し、システムのパフォーマンスを向上させることを目指しています。具体的には、ソケットイベントの取り扱いを簡素化し、コードの冗長性を削減することで、メンテナンスとパフォーマンスの両方を向上させます。
* #80 
- ソケットイベントハンドリングの集中化により、イベント管理がより一貫性をもって行われるようになりました。
- WebRTC関連の処理が改善され、接続の安定性が向上しました。
* なし
* ソケットイベントの処理ロジックに変更を加えた部分のロジックに特に注意してレビューをお願いします。
- 新しいイベント処理ロジックの動作確認
- システム全体のパフォーマンステスト
* #80 
* …
=> [MIN-145] WebSocketとWebRTCの統合を最適化するリファクタリング

main.go
* WebSocket通信を実現するための新しいエンドポイント /ws をサーバに設定しました。これにより、アプリケーションのリアルタイム通信機能が強化されます。
* #80 
* `/ws` のエンドポイントを通じてWebSocket接続を処理する新しいルートがGinルーターに追加されました。
* `handleConnections` 関数がWebSocketリクエストを処理するように統合されました。
* なし
* WebSocketの接続処理の安定性とエラーハンドリングの適切性を確認していただきたいです。
* 新しいWebSocketエンドポイントの動作確認が必要です。特に、複数のクライアントが同時に接続し、適切にメッセージを交換できるかを検証してください。
* #80 
* …
=> [MIN-145] WebSocketのエンドポイントを追加

controllers/chat_controller.go, main.go
* チャットAPIのレスポンス 메カニズムを改善し、より効率的で信頼性の高いサービスを提供するために、内部サービスロジックを最適化します。
* #229 
* 全エンドポイントのレスポンスフォーマットを統一しました。
* Redisとのインタラクションを効率化しました。
* なし
* Redisとのインタラクションの改善部分
* レスポンスフォーマットの一貫性
* なし
* #229 
* P3 : …
=> [MIN-182] チャットAPIのレスポンス最適化とサービスロジックの改善

services/chat_service.go
* ユーザーからのフィードバックを元に、チャット機能の使い勝手を向上させ、新たな機能を追加します。
* #229 
* ユーザーインターフェースの改善。
* 新しいメッセージング機能の追加。
* なし
* 新機能の統合の仕方とその影響。
* なし
* #229 
=> [MIN-182] チャット機能の細かい調整と新機能の実装

docs/docs.go, docs/swagger.json, docs/swagger.yaml
* 最新のAPI仕様に基づいてSwaggerドキュメントを更新し、開発者がAPIを正確に理解し使用できるようにします。
* #229 
* 新しいエンドポイントの説明を追加しました。
* 古い情報を削除または更新しました。
* なし
* 新しく追加されたエンドポイントの説明の明確さと正確性。
* なし
* #229 
=> [MIN-182] Swaggerドキュメントの全面的な更新

main.go, repositories/class_code_repository.go, services/class_code_service.go, services/class_service.go
* 新規クラス作成時に毎回ユニークなランダムクラスコードを自動生成する機能を実装することで、クラスの管理をより簡単かつ効率的に行うことができるようになります。この変更により、手動でのコード生成からの誤りを防ぎ、システム全体の信頼性が向上します。
* #233 
* [클래스 코드 생성 에러(クラスコード生成エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-273)
* `class_service` にランダムクラスコード生成機能を追加。
* 生成されたクラスコードの重複チェックロジックを `class_code_repository` に実装。
* 新規クラス作成のプロセスにクラスコード自動生成機能を組み込み。
* なし
* 生成されるランダムコードの形式（現在は英数字6文字）とそのユニーク性を保証するロジックに特に注目してレビューをお願いします。
* 自動生成されたクラスコードのユニーク性のテスト。
* 新規クラス作成機能全体の統合テスト。
* #233 
* [클래스 코드 생성 에러(クラスコード生成エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-273)
* …
=> [MIN-273] 新規クラス作成時に自動でランダムクラスコードを生成する機能の実装

controllers/user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/user_repository.go, services/user_service.go
* このPRでは、ユーザー名での検索機能とそのSwaggerドキュメントの追加を行いました。これにより、APIの使用者がユーザー名でユーザーを効率的に検索できるようになり、APIの可視性と利用しやすさが向上します。
* #235 
* [유저 검색(ユーザー検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-274)
* ユーザー名でユーザーを検索するAPIエンドポイントの追加。
* 新たに追加したエンドポイントのSwaggerドキュメントを作成しました。
* なし
* 検索機能の実装とドキュメントの記述において、特にSQLクエリの最適化とドキュメントの詳細度に注意してください。
* 新たに追加した検索機能の統合テスト。
* Swaggerドキュメントのリンクとフォーマットの検証。
* #235 
* [유저 검색(ユーザー検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-274)
* …
=> [MIN-274] ユーザー名検索機能とSwaggerドキュメントの追加

controllers/class_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, dto/class_dto.go, models/class_code.go, services/class_service.go
* このPRでは、クラス作成時にパスワードを設定できるオプションを追加することで、クラスのセキュリティを向上させることを目指しています。これにより、クラスへの参加を制限し、管理者のみが許可したユーザーのみがクラスに参加できるようになります。
* #237 
* [클래스 생성시 비밀번호 설정 에러(クラス作成時のパスワード設定エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-275)
* `class_code` モデルに `Secret` 属性を追加してパスワードを保存できるようにしました。
* クラス作成フォームにパスワード入力フィールドを追加しました。
* APIのドキュメント（Swagger）を更新し、新しいパスワードフィールドの説明を追加しました。
* なし
* パスワードのバリデーションロジックを追加しましたので、その処理に特に注意を払ってレビューをお願いします。
* 新しいパスワードフィールドのAPIテストを追加しました。クラス作成と参加時のセキュリティが正しく機能するかの検証が必要です。
* #237 
* [클래스 생성시 비밀번호 설정 에러(クラス作成時のパスワード設定エラー)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-275)
* …
=> [MIN-275] クラス作成機能にパスワードオプションを追加

controllers/class_board_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/class_board_service.go
* クラス掲示板の情報が更新された際に、ユーザーがリアルタイムでその変更を確認できる通知機能を実装しました。また、この機能に関連するAPIの仕様をSwagger文書に追加しました。この変更により、ユーザーエクスペリエンスが向上し、システムの対話性が高まることが期待されます。
* #239 
* [Gin 알림 기능(Gin通知機能)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-276)
* クラス掲示板の各種操作（作成、更新、削除）に対するリアルタイム通知機能を追加しました。
* Swagger文書に新しいエンドポイントとその仕様を追加しました。
* なし
* 通知機能の実装ロジックとそのパフォーマンスに関してご確認いただきたいです。
* Swagger文書の記述が正確であるかどうかもご確認ください。
* 新しい通知機能のエンドポイントに対する統合テストを追加しました。テストが適切に設計されているかレビューをお願いします。
* #239 
* [Gin 알림 기능(Gin通知機能)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-276)
* …
=> [MIN-276] クラス掲示板の更新通知機能

controllers/chat_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, services/chat_service.go
* このPRでは、ユーザ間で交換されたダイレクトメッセージを削除する機能を実装しました。プライバシー保護とデータの整理を目的として、不要なメッセージを安全に削除することができます。
* #241 
* `chat_controller`にダイレクトメッセージを削除する新しいDELETEエンドポイントを追加しました。
* `services.Manager`にRedisから特定のユーザー間のメッセージを削除するロジックを実装しました。
* Swaggerドキュメントを更新し、新しいAPIエンドポイントの詳細を追加しました。
* なし
* 削除機能の実装に関して、特にRedisのキー操作が適切に行われているかを中心にレビューをお願いします。
* 新しく追加されたエンドポイントの統合テストが必要です。特にエラーハンドリングと正常系の動作確認をお願いします。
* #241 
* …
=> [MIN-182] ダイレクトメッセージ削除APIの実装とドキュメント更新

controllers/user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/user_repository.go, services/user_service.go
- 会員が自身のアカウントを簡単かつ安全に削除できる機能を実装しました。これにより、ユーザーのプライバシー保護とデータ管理の透明性が向上します。
- 関連ドキュメントや設計図は特にありませんが、標準的な会員管理機能の一環として実装されました。
- ユーザーが自分のアカウントを削除するためのUIとバックエンドのロジックが追加されました。
- アカウント削除後、ユーザーのデータは安全に削除され、必要な場合には適切なデータ保護規則に従って処理されます。
- なし
- アカウント削除のバックエンドロジックのセキュリティ対策が適切かどうか、特に確認いただきたいです。
- アカウント削除機能の統合テストと、削除後のデータハンドリングのテストが必要です。
- #243 
- [유저 탈퇴(ユーザー削除)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-277)
* P2 : …
=> ユーザー削除機能の実装

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_user_service.go
* このPRでは、ユーザーが登録しているクラスを簡単に検索できるようにする新しいAPI機能を実装しました。また、この新機能に対応するSwaggerドキュメントも更新しています。この変更はユーザーインターフェースの使い勝手を向上させることを目的としています。
* #245 
* [클래스 검색(クラス検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-281)
* ユーザーが参加しているクラスを名前で検索するためのAPIエンドポイントを追加しました。
* Swagger UIでのAPIのドキュメンテーションを更新しました。
* なし
* 新しく追加されたAPIエンドポイントのコードおよびドキュメントの記述に特に注意してレビューをお願いします。
* 追加されたAPIエンドポイントの機能テストが必要です。
* Swaggerドキュメントの正確性を確認するためのレビューが必要です。
* #245 
* [클래스 검색(クラス検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-281)
* …
=> [MIN-281] ユーザー登録クラス検索機能

dto/class_user_dto.go, models/class_user.go, models/role.go, repositories/class_user_repository.go, repositories/role_repository.go, repositories/user_repository.go, services/class_service.go, services/class_user_service.go
- 会員が自身のアカウントを簡単かつ安全に削除できる機能を実装しました。これにより、ユーザーのプライバシー保護とデータ管理の透明性が向上します。
- 関連ドキュメントや設計図は特にありませんが、標準的な会員管理機能の一環として実装されました。
- ユーザーが自分のアカウントを削除するためのUIとバックエンドのロジックが追加されました。
- アカウント削除後、ユーザーのデータは安全に削除され、必要な場合には適切なデータ保護規則に従って処理されます。
- なし
- アカウント削除のバックエンドロジックのセキュリティ対策が適切かどうか、特に確認いただきたいです。
- アカウント削除機能の統合テストと、削除後のデータハンドリングのテストが必要です。
- #247 
- - [DB 통합(DB統合)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-282)
- P2 : …
=> データベース合併についての修正

middlewares/authentication_middleware.go, migration/migration.go
- ミドルウェアとマイグレーションファイルのロジックに追加の変更が必要でした。これにより、特定の機能の改善やバグ修正が行われます。
- ミドルウェアとマイグレーションファイルのロジックが修正されました。
- なし
- ミドルウェアとマイグレーションファイルのロジックの改訂が、予定通りの機能実装に適しているかどうか、特に確認いただきたいです。
- ミドルウェアとマイグレーションファイルの修正に関連する統合テストと、機能のテストが必要です。
- #247 
- P3 : …
=> データベース合併についてのミドルウェアとマイグレーションの修正

repositories/class_user_repository.go
- クラス「ユーザー」に関連するリポジトリ層のコードを修正しました。これにより、特定の機能の改善やバグ修正が行われます。
- クラス「ユーザー」に関連するリポジトリ層のコードが修正されました。
- なし
- クラス「ユーザー」に関連するリポジトリ層のコードの改訂が、予定通りの機能実装に適しているかどうか、特に確認いただきたいです。
- クラス「ユーザー」に関連するリポジトリ層の修正に関連する統合テストと、機能のテストが必要です。
- #247 
- P3 : …
=> クラスユーザーレポジトリの修正

controllers/class_board_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, repositories/class_board_repository.go, services/class_board_service.go
* クラス掲示板の検索機能を実装し、ユーザーが特定の掲示板をタイトルとクラスIDで検索できるようにします。この機能は、ユーザーが掲示板を効率的に見つけるのに役立ちます。
* #255 
* [클래스 게시글 검색(クラス投稿検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-290)
* コントローラ、サービス、リポジトリにクラス掲示板の検索機能を追加しました。
* SwaggerドキュメントにAPIのエンドポイントを追加しました。
* なし
* 新しい検索ロジックが適切に動作するかを確認してください。
* クラス掲示板の検索機能のテストが必要です。
* #255 
* [클래스 게시글 검색(クラス投稿検索)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-290) …
=> [MIN-290] クラス掲示板の検索機能の実装

main.go
* WebRTC関連のロジックを確認して、画面共有機能の実装に関する問題を解決します。具体的には、画面共有セッションの安定性や接続のパフォーマンスに影響を与える可能性のある問題に対処することを目指しています。
* #80
* WebRTCのロジックに関するコードのチェックと最適化
* 画面共有機能の接続安定性の向上
* なし
* WebRTCロジックの改善点に関する部分
* 画面共有機能の接続の安定性をテストしてください。
* #80
* P2 : …
=> [MIN-145] 画面共有のためのWebRTCロジックチェックを実装

repositories/class_code_repository.go
- SaveClassCode 関数に、UIDとCIDの有効性を事前に検証するロジックを追加しました。これにより、特定の機能の改善やバグ修正が行われます。
- SaveClassCode 関数に、UIDとCIDの有効性を事前に検証するロジックが追加されました。
- なし
- SaveClassCode 関数内でのUIDとCIDの検証ロジックが、適切に実装されているかどうか、特に確認いただきたいです。
- SaveClassCode 関数の修正に関連する統合テストと、機能のテストが必要です。
- #247 
- P2 : 反映を積極的に検討していただければと思います …
=> UIDとCIDの有効性を検証するロジックを追加

.github/workflows/cd.yml, docker-compose.yml
* このPRでは、バックエンドアプリケーションの無停止デプロイメントを実現するためにDockerおよびCI/CD設定を最適化しました。これにより、デプロイ中のサービス停止時間を最小限に抑え、より効率的なアップデートプロセスを提供します。
* #260 
* `docker-compose.yml` において環境変数のマウント方法を改善しました。
* `cd.yml` でCI/CDワークフローを更新し、Dockerイメージのプルとアップデートをより効率的に行えるようにしました。
* なし
* CI/CD設定の最適化における`docker-compose`コマンドの適用方法に特に注意してレビューしていただきたいです。
* 実際のデプロイメントプロセスで無停止が実現できるかの確認が必要です。
* 新しいCI/CDフローによるビルドとデプロイメントの成功確認。
* #260 
* …
=> [MIN-205] 無停止デプロイメントのためのDockerおよびCI/CD設定の最適化

.github/workflows/cd.yml, .github/workflows/ci.yml
* このPRでは、CI/CDワークフローに`workflow_dispatch`イベントを追加して、手動でワークフローをトリガーできるようにすることを目指します。これにより、開発者が必要に応じてワークフローを起動できる柔軟性が向上します。
* #260 
* `ci.yml`および`cd.yml`ファイルに`workflow_dispatch`トリガーを追加しました。
* なし
* 追加された`workflow_dispatch`の設定に誤りがないか、ご確認をお願いします。
* 追加されたトリガーが正しく機能するかの検証が必要です。手動トリガーを使用してワークフローが適切に起動するかを確認してください。
* #260 
* …
=> [MIN-205] CI/CDワークフローにworkflow_dispatchを追加

.github/workflows/cd.yml
* 本PRでは、CDワークフローにおいてDocker Composeコマンドを実行する前に正しい作業ディレクトリへの移動を保証することを目的としています。これにより、デプロイメントプロセス中に発生していたパス関連の問題を解決します。
* #260 
* `cd.yml`ファイルにおいて、SSHコマンド実行前に正確なディレクトリへ移動するためのコマンドラインを追加しました。
* なし
* 新たに追加されたディレクトリ変更コマンドのシンタックスとその配置を特に確認していただきたいです。
* 変更されたワークフローが正しく動作するかどうか、具体的にDocker Composeコマンドが期待通りに実行されるかの確認が必要です。
* #260 
* …
=> [MIN-205] CDワークフローの作業ディレクトリ設定の最適化

.github/workflows/cd.yml
* デプロイメントスクリプトの不具合を修正しました。`cd.yml`におけるプロジェクトのディレクトリパスが正しくなかったため、正しいパスに更新する必要がありました。この修正により、デプロイメントプロセスが正常に機能するようになります。
* #260 
* `cd.yml`ファイル内のデプロイメントパスを`/home/ubuntu/project_minori-gin-deployment-repo`から`project_minori-gin-deployment-repo`に更新しました。
* なし
* 特にありませんが、パスの指定が適切かどうか確認していただきたいです。
* デプロイメントスクリプトの実行を通じて、パスが正しく設定されたかを確認する必要があります。
* #260 
* …
=> [MIN-205] デプロイメントパスの誤りを修正

.github/workflows/ci.yml
* CI/CDパイプラインのDockerイメージをビルドする際に発生していたキャッシュ関連の問題を解決します。これにより、常に最新のコードベースからイメージを構築することが可能となります。
* #260 
* Docker Buildxアクションに `no-cache: true` オプションを追加し、ビルドプロセス中にキャッシュを使用しないようにしました。
* なし
* ビルドの安定性と再現性に関する変更を行っていますので、特にビルドプロセスの部分を重点的に確認していただきたいです。
* CIパイプラインでのビルドが成功し、最新のイメージが正しくプッシュされるかを確認する必要があります。
* #260 
* …
=> [MIN-205] CIワークフローのDockerビルドでキャッシュを無効に

Dockerfile
* このPRでは、Dockerビルドプロセス中に不要なモジュールを削除し、依存関係を整理することを目的としています。これにより、ビルドの効率が向上し、将来の依存関係管理が容易になります。
* #260 
* `Dockerfile`に`RUN go mod tidy`コマンドを追加しました。これにより、Goの依存関係を整理し、プロジェクト内の不要な依存関係を削除します。
* なし
* `go mod tidy`の追加によるDockerビルドプロセスへの影響を確認していただければと思います。
* この変更によりビルド時間が短縮されるかどうかの確認が必要です。
* #260 
* …
=> [MIN-205] Dockerfileに`go mod tidy`を追加

.github/workflows/cd.yml
* このPRでは、EC2へのデプロイメント手順を更新し、より効率的なコンテナ管理を実現します。以前のdocker-composeを使用したコマンドから、直接的なDockerコマンドに変更することで、プロセスの明瞭化と最適化を図ります。
* #260 
* 以前のdocker-composeを利用したデプロイメントコマンドが、Dockerの直接コマンドへと変更されました。新しい手順では、最新のイメージをpull後、既存のコンテナを停止・削除し、新しいコンテナを起動します。これにより、不要なイメージをクリーンアップし、EC2インスタンス上のストレージ管理を改善します。
* なし
* 新しいデプロイメントコマンドの効率性と、可能なセキュリティリスクについてフィードバックをお願いします。
* デプロイメント後のアプリケーションの正常動作を確認するため、実際のデプロイテストが必要です。
* #260 
* …
=> [MIN-205] EC2デプロイメントコマンドの更新

services/class_service.go
- クラスの作成時に、クラスユーザーテーブルに追加する必要がある情報を追加するロジックを修正しました。これにより、特定の機能の改善やバグ修正が行われます。
- クラスの作成時に、クラスユーザーテーブルに追加する必要がある情報を追加するロジックが修正されました。
- なし
- クラスの作成時に追加される情報の追加ロジックが、適切に実装されているかどうか、特に確認いただきたいです。
- クラスの作成時に追加される情報の追加に関連する統合テストと、機能のテストが必要です。
- #247 
- P3 …
=> クラス生成時入力される情報の追加

repositories/user_repository.go, services/class_service.go
- クラス作成時に、クラスユーザーの情報を保存する際に、基本的なニックネームをユーザー名から取得するように修正しました。これにより、特定の機能の改善やバグ修正が行われます。
- クラス作成時に、クラスユーザーの情報を保存する際に、基本的なニックネームをユーザー名から取得するようにするロジックが修正されました。
- なし
- クラス作成時に、クラスユーザーの情報を保存する際の基本的なニックネームの取得ロジックが、適切に実装されているかどうか、特に確認いただきたいです。
- クラス作成時に、クラスユーザーの情報を保存する際の基本的なニックネームの取得に関連する統合テストと、機能のテストが必要です。
- #247 
- P1 : 必ず反映してください (Request Changes) - …
=> クラス内の基本的なニックネームの設定

main.go
- main.goでNewCreateClassServiceに不足している引数を与えたことで、修正しました。これにより、特定の機能の改善やバグ修正が行われます。
- main.goでNewCreateClassServiceに不足している引数を与えたことで、修正しました。
- なし
- main.goでNewCreateClassServiceに不足している引数を与えたことで、修正した部分が適切に実装されているかどうか、特に確認いただきたいです。
- main.goでNewCreateClassServiceに不足している引数を与えたことで、修正した部分に関連する統合テストや機能のテストが必要です。
- #247 
- P1 : 必ず反映してください (Request Changes) - …
=> 不足のアーギュメントの追加

controllers/class_user_controller.go
- 受け取った招待に関連するクラスのリストを取得できるようにするため、ロジックの修正が必要です。
- クラスのリストを取得するための新しいロジックが実装されました。
- これにより、ユーザーが受け取った招待に関連するクラスを簡単に閲覧できるようになります。
- なし
- 新しいロジックが正しく実装されているかどうか、特に確認いただきたいです。
- 新しいクラス取得ロジックに関連する統合テストと、UIの変更に関連するテストが必要です。
- #273 
=> GetUserClassesByRoleの修正

controllers/class_user_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
- GetUserClassesByRoleメソッドの変更に伴い、スワッガーの注釈を修正しました。
- GetUserClassesByRoleメソッドの変更に対応して、スワッガーの注釈を更新しました。
- これにより、APIのドキュメントが最新の状態になります。
- なし
- スワッガーの注釈が変更に合わせて適切に更新されているかどうか、特に確認いただきたいです。
- スワッガーの注釈を修正した部分に関するテストや確認が必要です。
- #273 
=> Swaggerのコメントの修正

main.go
- ChangeUserRoleルーティングで、パラメータroleをroleNameに変更しました。
- ChangeUserRoleルーティングで、パラメータroleをroleNameに変更しました。
- これにより、パラメータの名前がより意味のあるものに変更されました。
- なし
- パラメータ名の変更が正しく行われているかどうか、特に確認いただきたいです。
- パラメータ名の変更に関連するテストや確認が必要です。
- 現時点で特に関連するIssueやドキュメントはありません。
=> ルーティングのパラメートルの修正

main.go
- GetClassMembersハンドラーのルーティングが間違っていたため、修正しました。
- GetClassMembersハンドラーのルーティングが間違っていたため、修正しました。
- これにより、正しいルーティングが設定され、APIの正しい動作が期待されます。
- なし
- GetClassMembersハンドラーの修正が正しく行われているかどうか、特に確認いただきたいです。
- GetClassMembersハンドラーの修正に関連するテストや検証が必要です。
- #273 
=> GetClassMembersメッソドのルーティングの修正

controllers/class_code_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/class_user_repository.go, services/class_code_service.go, services/class_user_service.go
- クラスコードを入力し、パスワードの有無をチェックして、クラスに入室リクエスト状態に変更するためのロジックを実装しました。
- クラスコードを入力し、パスワードの有無をチェックして、クラスに入室リクエスト状態に変更するためのロジックを実装しました。
- これにより、クラス入室のプロセスが自動化され、より効率的になります。
- なし
- パスワードの有無をチェックして、クラスに入室リクエスト状態に変更するロジックが正しく実装されているかどうか、特に確認いただきたいです。
- 新しいロジックに関連するテストや検証が必要です。
- #273 
=> クラスコードによるクラス加入申し込みの実装

main.go
* AWSロードバランサーからのクロスオリジンリクエストを許可するため、CORS設定を更新しました。これにより、新しいクライアント側のデプロイがバックエンドに安全にアクセスできるようになります。設定変更の必要性は、最近のフロントエンドの変更によるもので、セキュリティとアクセシビリティの向上が期待されます。
* #68 
* `http://minori-next-lb-1326724168.ap-northeast-2.elb.amazonaws.com` がCORS許可リストに追加されました。これは、AWSのロードバランサーからのリクエストを許可するための変更です。
* なし
* 更新されたCORS設定の適用範囲とセキュリティ影響について、特に注意深く確認していただきたいです。
* 新しいCORS設定が正しく機能するかどうか、異なるオリジンからのリクエストを使って検証が必要です。
* #68 
* …
=> [MIN-291] CORS設定の更新：AWSロードバランサーからのアクセスを許可

main.go
* このPRでは、CORSミドルウェアを更新して、許可されたオリジンのリストに対して着信リクエストのオリジンを動的に検証します。これにより、信頼できるソースからのリクエストのみを受け入れることで、セキュリティを強化し、オリジン検証の柔軟性を向上させます。
* #68 
* リクエストヘッダから `Origin` を読み取り、許可されたオリジンリストと比較するロジックを追加しました。一致する場合にのみ `Access-Control-Allow-Origin` ヘッダを設定し、CORSリクエストを許可します。
* なし
* 新しいCORS検証ロジックの効率性とセキュリティに関して意見をいただければと思います。
* 新しいミドルウェア設定によるオリジンの検証機能について、異なるオリジンからのリクエストを試して正常に拒否されるかを確認してください。
* #68 
* …
=> [MIN-291] 動的なオリジン検証をサポートするCORSミドルウェアの更新

main.go
* CORS設定が不足しており、特定のオリジンからのリクエストが拒否されていました。
* #68 
* `minoriedu.com` からのリクエストを許可するためにCORS設定を追加しました。
* なし
* CORS設定の適用範囲とセキュリティ影響について確認をお願いします。
* ローカル環境でのCORSリクエストのテストが必要です。
* #68 
=> [MIN-291] minoriedu.comに対するCORS設定の追加

main.go
* CORS設定が不足しており、特定のオリジンからのリクエストが拒否されていました。
* #68 
* `minoriedu.com` からのリクエストを許可するためにCORS設定を追加しました。
* なし
* CORS設定の適用範囲とセキュリティ影響について確認をお願いします。
* ローカル環境でのCORSリクエストのテストが必要です。
* #68 
=> [MIN-291] ECSに対するCORS設定の追加

main.go
* Swagger UIにアクセスする際に発生する403エラーを解決するために、CORSのOPTIONSメソッドに対するオリジンチェックをコメントアウトしました。
* #68 
* CORSのOPTIONSメソッドに対するオリジンチェックをコメントアウトしました。
* なし
* Swagger UIにアクセスする際に403エラーが発生しなくなったかどうか確認してください。
* Swagger UIへのアクセスをテストして、403エラーが発生しないことを確認してください。
* #68 
* P2 : …
=> [MIN-291] CORSのOPTIONSメソッドチェックをコメントアウトして403エラーを修正

main.go
- 許可された出所からのOPTIONSリクエストは204ステータスで応答し、許可されていない出所からのリクエストは403ステータスで応答するようにするロジックを修正しました。
- 許可された出所からのOPTIONSリクエストは204ステータスで応答し、許可されていない出所からのリクエストは403ステータスで応答するようにするロジックを修正しました。
- これにより、セキュリティ上の理由から正しい応答ステータスが送信され、アプリケーションのセキュリティが向上します。
- なし
- CORS処理のロジックが正しく動作しているか確認してください。
- CORS処理の変更に関連するテストや検証が必要です。
- #101 
- [CORS 문제해결](https://okura-minori.atlassian.net/browse/MIN-279)
=> CORSによるレスポンスの修正

main.go
- スワッガーへのアクセスが403エラーで拒否されている問題を解決するため、ignoredPathsにSwaggerへのアクセスに関するパスを修正しました。
- スワッガーへのアクセスが403エラーで拒否されている問題を解決するため、ignoredPathsにSwaggerへのアクセスに関するパスを修正しました。
- なし
- スワッガーへのアクセスに関する修正が正しく機能しているか確認してください。
- この変更に関連するテストや検証が必要です。
- #101 
- [CORS 문제해결](https://okura-minori.atlassian.net/browse/MIN-279)
* レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
* レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
* レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
=> ignorePathの修正

main.go
- ignoredPathsに含まれるパスがリクエストパスのプレフィックスであるかどうかを確認するロジックを変更しました。
- ignoredPathsに含まれるパスがリクエストパスのプレフィックスであるかどうかを確認するロジックを変更しました。
- なし
- パスのプレフィックスの確認が正しく機能していることを確認してください。
- この変更に関連するテストや検証が必要です。
- #101 
- [CORS 문제해결](https://okura-minori.atlassian.net/browse/MIN-279)
* レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
* レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
* レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
=> リクエストパスのプレフィックスをチェックするロジックの修正

controllers/chat_controller.go, controllers/class_controller.go, controllers/class_user_controller.go, controllers/google_auth_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
* Swaggerドキュメントのサマリーおよびパラメーターの説明をコンベンションに従って更新しました。
* #9 
* [Swagger API 문서화(Swagger APIのドキュメント)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-292)
* Swaggerのサマリーおよびパラメーターの説明、名前をコンベンションに従って修正。
* なし
* Swaggerドキュメントの変更が意図した通りに反映されているかどうかをご確認ください。
* なし
* #9 
* [Swagger API 문서화(Swagger APIのドキュメント)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-292)
* …
=> [MIN-292] Swaggerのサマリーとパラメーターの説明を更新

Dockerfile
* このPRでは、現在のDockerfileを最適化し、ビルドの効率を向上させ、生成されるイメージサイズを削減します。これにより、デプロイメントの速度を改善し、リソースの無駄を減らします。
* #292 
* 依存関係のキャッシュを設定し、Dockerのキャッシュメカニズムを活用しました。
* ソースコードをコピーする前にビルドツールをインストールして、レイヤーキャッシュを利用しました。
* 一貫性のあるビルドのために、指定された環境変数でアプリケーションをビルドしました。
* より小さな最終イメージサイズのために、最小限のランタイムイメージ（Alpine）を使用しました。
* なし
* キャッシュの設定とビルドプロセスの最適化部分に特に注目していただければと思います。
* ビルドとランタイム環境での動作確認が必要です。特に、新しいDockerfileで生成されたイメージが正しく動作するかどうかを確認してください。
* #292 
* …
=> [MIN-293] Dockerfileの最適化

.github/workflows/ci.yml, .ko.yaml
* このPRでは、`ko`を使用してGoアプリケーションのビルドプロセスを簡素化し、Dockerイメージの作成を最適化します。これにより、ビルドプロセスが簡略化され、効率が向上します。
* #292 
* `.ko.yaml`ファイルを追加し、デフォルトのベースイメージを設定しました。
* GitHub Actions CIワークフローを更新し、`ko`を使用してイメージをビルドおよびプッシュするようにしました。
* 不要なDockerfileのステップを削除しました。
* なし
* `ko`の設定とGitHub Actionsのワークフローが正しく動作するかどうかに注目してください。
* `ko`の設定とGitHub Actionsのワークフローが正しく動作するかどうかに注目してください。
* #292 
* …
=> [MIN-293] `ko`によるGoアプリケーションのビルド統合

.github/workflows/ci.yml
* このPRは、GitHub Actions CIワークフローで使用するGoのバージョンを1.21に更新し、koツールとの互換性を確保するためのものです。koはGo 1.21を必要とするため、現在の1.19から1.21に更新する必要があります。
* #292 
* GitHub ActionsのCIワークフローにおいて、Goバージョンを1.19から1.21に更新しました。
* なし
* 新しいバージョンのGoでのビルドプロセスが正常に動作するかどうかを確認してください。
* GitHub Actionsワークフロー全体のテストが必要です。
* #292 
* …
=> [MIN-293] Goバージョンを1.21に更新してkoの互換性を確保

.github/workflows/ci.yml
* このPRでは、GitHub Actionsのワークフローを最適化し、最新のガイドラインに従うように更新しました。これにより、ビルド時間の短縮とCIの効率化を図ります。
* #292 
* `set-output` コマンドを環境ファイルに置き換えました。
* Goモジュールのキャッシュを追加し、ビルド時間を短縮しました。
* `ko` のインストールを `go install` から `go get -u` に変更しました。
* `actions/setup-go` を v2 から v3 に更新しました。
* なし
* 特にありませんが、ワークフローの変更が適切かどうかを確認してください。
* すべてのCIワークフローが正しく実行されることを確認するため、ビルドおよびテストが必要です。
* #292 
* …
=> [MIN-293] GitHub Actionsのビルド時間最適化および最新ガイドライン適用

.github/workflows/ci.yml
* このPRでは、GitHub Actionsのワークフローを最適化し、最新のガイドラインに従うように更新しました。これにより、ビルド時間の短縮とCIの効率化を図ります。
* #292 
* Goのバージョンを1.22にアップデートしました。
* なし
* 特になし
* なし
* #292 
* P3 …
=> [MIN-293] Goバージョンを1.22にアップデートし、CIワークフローを最適化

.github/workflows/ci.yml
* このPRでは、GitHub Actionsのワークフローにkoをインストールし、PATHに追加します。これにより、ビルドプロセスでkoを使用してDockerイメージを作成し、プッシュできるようになります。
* #292 
* `ko`を`go install`を使用してインストール
* PATH環境変数にGoのバイナリディレクトリを追加
* なし
* koのインストール方法とPATHの設定が正しいか確認してください
* ビルドプロセスが正常に完了し、Dockerイメージが正しく生成されるかどうか
* #292 
* …
=> [MIN-293] Docker Image CIワークフローにkoインストールとPATH設定を追加

controllers/class_controller.go, repositories/class_code_repository.go, services/class_service.go
- クラスを検索する際に、該当するクラスコードも一緒に検索する機能の修正が完了しました。
- クラスを検索する際に、関連するクラスコードも一緒に検索できるようになりました。
- なし
- クラスコードが適切に検索されることを確認してください。
- この変更に関連するテストや検証が完了しました。
- #299 
* レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
* レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
* レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
=> クラス情報にクラスコードを追加

main.go
- ミドルウェアの順序により、Swaggerがすべての操作で403エラーを返している問題を修正しました。
- ミドルウェアの順序を修正して、Swaggerが正常に動作するようにしました。
- なし
- Swaggerのエラーが修正されていることを確認してください。
- この変更に関連するテストや検証が完了しました。
- #301 
* レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
* レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
* レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
=> initializeSwaggerメッソドの呼び順番の修正

main.go
* 不要なWebRTCロジックがコードベースに含まれていたため、アプリケーションのシンプル化と保守性向上のために削除しました。
* データベースの移行に関する権限の問題を回避するため、移行プロセスを除去し、データベースに接続するだけのシンプルな設定に変更しました。
* Swaggerのリンクが403エラーを引き起こしていたため、正しいリンクとパーミッションに修正しました。
* WebRTC関連のすべてのコードを削除しました。
* データベース移行のロジックを削除し、接続のみを設定するようにしました。
* Swaggerのエンドポイントが正しく動作するようにリンクを修正しました。
* なし
* Swaggerリンクの修正が他のAPIへの影響を及ぼさないか確認してください。
* データベース接続設定の変更が意図通りに動作するかどうか、見ていただけると助かります。
* データベース接続の動作確認
* Swaggerドキュメントの正しい表示
* #304 
* …
=> [MIN-300] ♻️ WebRTCロジックの削除とデータベース移行の除去、およびSwaggerリンクの修正

controllers/class_controller.go, repositories/class_code_repository.go, services/class_service.go
* クラス情報を取得するAPI (GetClass) が、クラスコードとシークレットを含まずにクラスの基本情報のみを返している問題を解決します。この問題は、クラスコードとシークレットが必要なクライアントアプリケーションに影響を与えます。
* クラスの情報を取得する際に、クラスコードとシークレットを含めるようにしました。
* `repositories/class_code_repository.go` の `FindByClassID` メソッドにログを追加し、デバッグを容易にしました。
* `services/class_service.go` の `GetClassWithCode` メソッドで、クラスコードの取得とログの出力を行うようにしました。
* `controllers/class_controller.go` の `GetClass` メソッドで、クラスコードとシークレットをレスポンスに含め、取得データをログに出力するようにしました。
* 特になし。
* クラスコードとシークレットが正しく取得され、APIレスポンスに含まれているかを確認してください。
* ログ出力の内容がデバッグに役立つかどうか、また不要な出力がないかをご確認ください。
* クラスコードとシークレットを含むクラスの情報取得が正常に行われるかを確認するテスト。
* クラスコードやシークレットが存在しない場合の動作も確認する必要があります。
* #304 
> …
=> [MIN-300] クラス情報取得APIにクラスコードとシークレットを含める

controllers/class_controller.go
* クラス情報を取得する際、クラスコードとシークレットも一緒に返却する必要がありました。しかし、既存のロジックではクラスコードが返却されない問題が発生していました。これにより、特定の操作やユーザーエクスペリエンスに影響が出ていました。
* GetClassメソッドのレスポンスロジックを修正し、クラスコードとシークレットが存在する場合に正しく返却されるようにしました。
* クラスとクラスコードの詳細をトレースするためのログを追加し、デバッグが容易になるようにしました。
* なし
* クラスコードとシークレットのレスポンス部分が正しく動作しているかを確認してください。
* ログの出力が意図した通りに動作しているかを確認してください。
* クラスコードとシークレットが正しく返却されるかどうかのテスト
* ログ出力が適切に行われるかどうかの確認
* #304 
* …
=> [MIN-300] クラス情報取得の際にクラスコードとシークレットを含める修正

controllers/class_controller.go, services/class_code_service.go, services/class_service.go
* GetClass エンドポイントがクラス情報を取得する際に、関連するクラスコードとシークレットを含めて返却しない問題を修正します。これにより、クラスコードとシークレットが存在する場合、それらを正しく返却し、フロントエンドでの利用を可能にします。
* GetClass メソッドのロジックを修正し、クラスコードとシークレットを含めて返却するようにしました。
* ClassCodeRepository において、クラスIDに基づいてクラスコードを正しく取得できるようにし、取得時のログを追加しました。
* サービス層 (ClassService) で、クラスとクラスコードの取得処理に詳細なロギングを追加しました。
* なし
* GetClass メソッドのレスポンスロジックが適切かどうか、および ClassCodeRepository でのクラスコード取得処理が正しく機能しているかを確認していただきたいです。
* GetClass エンドポイントでクラス情報を取得する際に、クラスコードとシークレットが存在する場合に正しく返却されることを確認するテスト。
* クラスIDに基づいてクラスコードを取得するロジックが期待通りに動作することを確認するテスト。
* #304 
* …
=> [MIN-300] クラス情報取得機能の改良: クラスコードとシークレットの返却対応

controllers/class_code_controller.go
* CheckSecretExists関数の呼び出しにおいて、引数が多すぎるエラーが発生していました。このPRでは、適切な引数で関数を呼び出すよう修正し、エラーを解消しました。
* CheckSecretExists関数の呼び出しにおいて、余分な引数を削除し、適切な引数で関数を呼び出すように修正しました。
* この修正により、ランタイムエラーが解消され、正常にクラスコードとその関連情報を取得できるようになりました。
* なし
* CheckSecretExists関数の呼び出し部分の変更点が、他の機能に影響を与えないことを確認してください。
* 修正後に、クラス情報取得時にクラスコードおよびシークレットが正しく返されることを確認してください。
* GetClassエンドポイントを通じて、クラス情報を取得する際にクラスコードとシークレットが正しく返されるかをテストする必要があります。
* #304 
* …
=> [MIN-300] CheckSecretExists関数の呼び出しエラーを修正

controllers/class_controller.go, main.go
* クラス情報を取得する際に、クラスコードとシークレットがレスポンスに含まれていない問題を修正しました。
* クラス情報を取得する `GetClass` メソッドを修正し、クラスコードとシークレットが正しくレスポンスに含まれるようにしました。
* クラスコードとシークレットが取得される状況を追跡するためのログを追加しました。
* レスポンスの構築を整理し、クラスコードとシークレットが確実に出力されるようにしました。
* なし
* `GetClass` メソッドのレスポンスにクラスコードとシークレットが含まれることを確認してください。
* ログが正しく出力され、クラスコードが正常に取得されることを確認してください。
* クラス情報取得時にクラスコードとシークレットが正しく返されるかをテストする必要があります。
* #304 
* …
=> [MIN-300] クラス情報にクラスコードとシークレットが含まれるように修正

controllers/class_controller.go
* クラス情報を取得する際に、クラスコードとシークレットがレスポンスに含まれていない問題を修正しました。クラスコードとシークレットが正しくレスポンスに含まれるようにし、データ構造を改善しました。
* `GetClass` メソッドを更新し、クラスコードとシークレットを正しくレスポンスに含めるようにしました。
* クラスコードとシークレットのレスポンス構造を改善し、利用可能な場合に常に提供されるようにしました。
* クラスとクラスコードの取得状況を追跡するためのログを追加しました。
* なし
* `GetClass` メソッドのレスポンスが、クラスコードとシークレットを正しく含むように変更されたことを確認してください。
* ログの追加により、クラスコードの取得が正常に行われていることを確認してください。
* クラス情報を取得する際に、クラスコードとシークレットが正しく返されることをテストする必要があります。
* #304 
* …
=> [MIN-300] クラス情報にクラスコードとシークレットを正しく含める修正

controllers/class_controller.go
* クラス情報を取得する際に、クラスコードの詳細がレスポンスに正しく含まれていない問題を修正しました。これにより、クラスとそのコードに関する完全な情報が返されるようになります。
* `GetClass` メソッドを更新し、クラスとクラスコードの情報が正しくフォーマットされてレスポンスに含まれるようにしました。
* クラスとクラスコードの詳細（ID、コード、シークレットなど）をレスポンスに追加しました。
* クラスとクラスコードの詳細（ID、コード、シークレットなど）をレスポンスに追加しました。
* クラスとクラスコードの取得手順を追跡するための詳細なログを追加しました。
* なし
* `GetClass` メソッドのレスポンスに、クラスとクラスコードの詳細情報が正しく含まれているかを確認してください。
* エラーメッセージが適切に処理され、ログによりクラスとクラスコードの取得手順が追跡されているかを確認してください。
* クラス情報を取得する際に、クラスコードの詳細が正しくレスポンスに含まれることをテストする必要があります。
* #304  …
=> [MIN-300] クラス情報にクラスコードの詳細を正しく含める修正

.github/workflows/ci.yml
* このPRは、Dockerイメージのビルドとプッシュのプロセスを改善し、GitHub Container Registry (ghcr.io) に適切にアップロードできるようにすることを目的としています。
* Docker Buildxのセットアップステップを追加しました。
* `docker/build-push-action@v3` を使用して、イメージをビルドし、ghcr.ioにプッシュするようにしました。
* `ko` を使用した古いビルド方法を削除しました。
* マルチプラットフォーム対応のため、`platforms` パラメータを追加しました。
* なし
* 新しいCIワークフローが期待通りにDockerイメージをビルドしてプッシュできるかどうか、特に`docker/build-push-action@v3`の設定と使用が正しいかを確認してください。
* CI/CDパイプラインを実行し、Dockerイメージがghcr.ioに正しくプッシュされることを確認してください。
* #177 
* …
=> [MIN-293] Docker CIワークフローの改善

controllers/class_controller.go
* このPRは、ClassControllerのGetClassメソッドのリファクタリングを目的としています。コードの可読性を向上させ、保守性を高めるための変更を行いました。
* `createClassResponse` 関数を導入し、レスポンス生成のロジックを簡素化しました。
* `respondWithError` および `respondWithSuccess` ユーティリティ関数を利用して、エラーハンドリングと成功時のレスポンス処理を改善しました。
* コード構造を整理し、不要な重複を削除しました。
* 詳細なログを追加し、トレース可能性を向上させました。
* なし
* 新たに導入した関数 `createClassResponse` の構造と、`respondWithError` および `respondWithSuccess` 関数の使用が適切であるか確認してください。
* 現行の機能を変更していないため、既存のテストがすべて正常に動作することを確認してください。
* #304 
* …
=> [MIN-300] ClassController: GetClass メソッドのリファクタリング (#304)

main.go
* Swagger URLに関連する設定が冗長であるため、これを簡素化し、メンテナンスしやすくするための変更です。
* `ignoredPaths`リストから重複するURLパターンを削除し、必要最小限のURLのみを残しました。
* なし
* 他に必要なSwagger URLパターンが見落とされていないか、確認をお願いします。
* 特にありませんが、Swaggerの設定が正しく動作することを確認するテストを推奨します。
* #301 
=> [MIN-291] 🐛 ignoredPathsの更新：swagger URLの整理

main.go
* Swagger UIを使用してAPIをテストする際に、403 Forbiddenエラーが発生する問題を解決するためです。このエラーは、CORS設定によりSwagger UIからのリクエストがブロックされるために発生していました。
* CORSの`allowedOrigins`リストにSwagger UIのURLを追加しました。これにより、Swagger UIからのリクエストがサーバーによって許可され、403エラーが解消されます。
* なし
* Swagger UIからのリクエストが正常に処理され、APIが期待通りに動作するかどうかを確認してください。また、CORS設定の影響を受ける他の部分がないかもご確認ください。
* Swagger UIを使用して、APIエンドポイントへのリクエストが正常に処理されるかを確認するテストが必要です。
* #301 
* P1 : 必ず反映してください (Request Changes) - …
=> [MIN-291] 🐛 fix: Swagger UIのCORS設定を更新して403エラーを解消

main.go
* Swagger UIを使用してAPIをテストする際に、特定のエンドポイントで403 Forbiddenエラーが発生する問題を解決するためです。このエラーは、CORS設定がSwagger UIからのリクエストを正しく処理していなかったために発生していました。
* CORSの`allowedOrigins`リストにSwagger UIのURLを追加し、さらに`/api/gin/cl/`パスを持つリクエストを明示的に許可する設定を追加しました。これにより、Swagger UIからのリクエストがサーバーで正しく処理されるようになります。
* なし
* Swagger UIからのリクエストが正常に処理され、APIが期待通りに動作するかどうかを確認してください。また、特に`/api/gin/cl/`パスへのリクエストに注目してください。
* Swagger UIを使用して、`/api/gin/cl/`パスへのAPIリクエストが正常に動作するかを確認するテストが必要です。
* #301 
* [CORS設定に関する関連ドキュメント](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-291)
* …
=> [MIN-291] 🐛 fix: Swagger UIからのリクエストに対するCORS設定を調整

main.go
* このPRでは、CORS設定を改善して、すべての`/api/gin/`で始まるAPIパスを許可するようにしました。
* これにより、Swagger UIや他のフロントエンドクライアントからのAPIアクセス時に発生する403エラーを解消します。
* CORS設定を更新して、`/api/gin/`で始まるすべてのリクエストを許可するようにしました。
* 既存の許可されたオリジンリストと無視されたパスのロジックを維持しました。
* なし
* CORS設定の変更がすべてのAPIパスに正しく適用されているかを確認してください。
* 特に、既存のAPIパスに対して403エラーが解消されたかどうかを確認してください。
* Swagger UIやフロントエンドクライアントからのAPIリクエストが正常に動作することをテストしてください。
* 新しいCORS設定が想定通りに機能することを確認してください。
* #301 
* [CORS設定に関する関連ドキュメント](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-291)
* P1 …
=> [MIN-291] CORS設定の改善：全てのAPIパスを許可

main.go
* 出席情報を追加または更新する際、/api/gin/atエンドポイントへのリクエストが404エラーを返す問題が発生していました。これにより、出席情報の管理が正常に行われませんでした。このPRでは、エンドポイントの設定を修正し、出席情報の作成と更新ができるようにします。
* 出席情報の作成および更新を処理するPOSTルートを/api/gin/atエンドポイントに追加しました。
* これにより、出席情報の作成または更新が可能になり、クライアントからのリクエストに対して適切に応答するようになります。
* 特にありません。
* /api/gin/atエンドポイントのルート設定が正しいかどうか。
* POSTリクエストを処理するAttendanceControllerのCreateOrUpdateAttendanceメソッドが正しく動作するかどうか。
* 出席情報の追加と更新が正しく処理されることを確認するために、手動および自動テストを実施する必要があります。
* 特に、異なるステータス（出席、欠席、遅刻）での動作確認が必要です。
* #325 
* [출석 API 개선(出席APIの改善)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-301)
* …
=> [MIN-301] 出席情報APIのPOSTルートの修正

controllers/attendance_controller.go, models/attendance.go, services/attendance_service.go
* 現行の出席管理システムでは、出席状態を文字列として扱っており、データの不整合やAPIエラーを引き起こす可能性がありました。特に、出席、遅刻、欠席といった状態が異なる形式で保存されたり比較されたりする問題がありました。
* このPRは、出席状態を統一された`AttendanceType`型として定義し、コード全体で一貫して使用することで、これらの問題を解決します。
* `models`パッケージに`AttendanceType`型を追加し、`ATTENDANCE`、`TARDY`、`ABSENCE`の標準的な出席状態を定義しました。
* `Attendance`構造体の`IsAttendance`フィールドを`AttendanceType`型に更新し、データベースのenum型と一致させました。
* `controllers/attendance_controller.go`の出席状態チェックと設定を`AttendanceType`を使用するように修正しました。
* `services/attendance_service.go`の出席状態の作成および更新ロジックを`AttendanceType`を使用するように変更しました。
* なし
* `models`パッケージで定義した`AttendanceType`が、`controllers`と`services`で正しく使用されているか確認してください。
* 出席状態が正しく標準化されているかどうか。
* 出席状態の作成、更新、取得、および削除が期待通りに機能しているか確認するためのテストが必要です。
* APIリクエストに対するレスポンスが正しい形式で返されるかを検証するテストも必要です。
* #325 
* [출석 API …
=> [MIN-301] 出席APIの改善と出席状態の標準化

controllers/attendance_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, models/attendance.go
* `GetAllAttendances`エンドポイントにリクエストを送信する際、`classID`が適切にパースされない問題を修正します。この問題は、URLパラメータの名前が一致しないことが原因であり、これにより、パラメータが正しく読み込まれず、エラーが発生していました。また、Swaggerドキュメントにおけるステータス名の不一致を修正しました。
* `GetAllAttendances`エンドポイントのURLパラメータ名を`classID`から`cid`に変更し、パラメータが正しくパースされるようにしました。
* Swaggerドキュメントで`ATTENDANCE`、`TARDY`、`ABSENCE`のステータス名が正しく記載されるように修正しました。
* なし
* `GetAllAttendances`のエンドポイントが正しく機能していることを確認してください。
* Swaggerドキュメントのステータス名の修正が正しく反映されていることを確認してください。
* `GetAllAttendances`エンドポイントへのリクエストが正常に処理されることを確認するテストを行いました。
* Swaggerドキュメントの更新がAPIドキュメントに反映されていることを確認しました。
* #325 
* [출석 API 개선(出席APIの改善)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-301)
* …
=> [MIN-301] GetAllAttendancesのクエリパラメータ修正とSwaggerドキュメントの更新

controllers/attendance_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, repositories/attendance_repository.go, services/attendance_service.go
* `GetAttendanceByID` メソッドのロジックを修正し、指定されたIDに関連するすべての出席情報を取得するようにしました。これにより、複数の出席情報が存在する場合にすべてのデータを正確に取得し、返すことができます。
1. `GetAttendanceByID` メソッドが単一の `models.Attendance` ではなく、`[]models.Attendance` を返すように変更しました。
2. `AttendanceController` における `GetAttendance` メソッドを修正し、複数の出席情報を正しく処理して返すようにしました。
3. `AttendanceService` 層での `GetAttendanceByID` メソッドを修正し、リポジトリ層の変更を反映しました。
4. Swagger ドキュメントを更新し、`GetAttendance` メソッドが配列を返すことを明示しました。
* なし
- `GetAttendanceByID` メソッドの変更が正しく複数の出席データを取得できるかどうかを確認してください。
- コントローラー層での `GetAttendance` メソッドが新しい配列形式のデータを正確に返しているかを確認してください。
- Swagger ドキュメントの変更が適切かどうかもご確認ください。
- 追加したユニットテストが正しく動作し、すべての関連する出席データを取得できることを確認する必要があります。
- 既存の他の機能やエンドポイントに影響がないことを確認する必要があります。
* #331 
* …
=> GetAttendanceByIDメソッドの修正: 指定IDの全ての出席情報を取得

controllers/attendance_controller.go, repositories/attendance_repository.go, services/attendance_service.go
* このPRは、出席情報を取得する際に関連するクラスユーザーの詳細情報を含める機能を追加します。これにより、APIのレスポンスがより充実し、ユーザーインターフェースで必要なデータを一度に取得できるようになります。
* attendance_repository の GetAttendanceByID メソッドを修正し、出席情報を取得する際に ClassUser データをプリロードするようにしました。
* attendance_service の GetAttendanceByID メソッドを更新し、プリロードされた ClassUser 情報を含む出席情報を返すようにしました。
* attendance_controller の GetAttendance メソッドを修正し、 ClassUser データを含む出席情報をクライアントに返すようにしました。
* なし
* attendance_repository での Preload の使用が適切か確認してください。
* attendance_service でのエラーハンドリングが適切であるかをチェックしてください。
* GetAttendance メソッドでのデータレスポンス形式が期待されるものと一致しているかを確認してください。
* 出席情報取得APIのレスポンスに ClassUser 情報が正しく含まれていることを確認するテスト。
* ClassUser 情報が適切にプリロードされていることを検証するためのエンドツーエンドテスト。
* 既存のユニットテストがこの変更によって影響を受けていないことを確認する回帰テスト。
* #334 
* …
=> 出席情報取得にクラスユーザー情報の追加

controllers/class_code_controller.go
* `VerifyAndRequestAccess`メソッドの成功時のレスポンスにクラスIDを含める機能を追加しました。この変更により、クライアントが検証後にクラスID（CID）を取得できるようになり、APIからの応答データがより有用になります。これにより、クライアント側でのクラスIDの管理とハンドリングが改善されます。
* VerifyAndRequestAccessメソッドのレスポンスにクラスID（CID）を含めました。
* クラスコードが検証され、ユーザーに役割が割り当てられた後、クラスIDも一緒に返されます。
* なし
* `VerifyAndRequestAccess`メソッドのロジックが適切にクラスIDをレスポンスに含めているかを確認してください。
* テストケースが新しい仕様をカバーしているかどうかもご確認いただきたいです。
* `VerifyAndRequestAccess`メソッドがクラスIDを含むレスポンスを正しく返すことを検証するためのテストを追加しました。
* #336 
* [가입 API 개선(加入APIの改善)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-303)
* …
=> [MIN-303] VerifyAndRequestAccessのレスポンスにクラスIDを含める

main.go
* Nginxの設定で、特定のドメイン（[https://minoriedu.com:80）からのCORSリクエストを許可する必要があります。これにより、ウェブアプリケーションのセキュリティを維持しながら、指定されたドメインからのリソースアクセスを可能にします。
* Nginx設定ファイルのallowedOriginsリストに"[https://minoriedu.com:80"を追加しました。
* CORS設定を更新し、指定されたドメインからのリクエストを許可するようになりました。
* なし
* 追加したオリジンが正しいフォーマットで記述されているか確認をお願いします。
* この変更がセキュリティに悪影響を与えないかの確認をお願いします。
* Nginx設定の構文チェック
* 実際に[https://minoriedu.com:80からのリクエストが正常に処理されるか
* 他の許可されていないオリジンからのリクエストが適切にブロックされるか
* #342 
* P2 : …
=> allowedOriginsのURL追加

.github/workflows/ci.yml, tests/attendance_controller_test.go, tests/integration_test.go
* 統合テストを実装し、CIパイプラインでのテスト実行を分離することで、テストの信頼性と効率を向上させます。
* 統合テストのロジックを追加し、ci.ymlで統合テストを別々に実行するように設定しました。
* `integration_test.go`に統合テストロジックを追加しました。
* `ci.yml`を更新し、統合テストを別々に実行するようにしました。
* 統合テストでのデータベースの初期化とクリーンアップを修正しました。
* なし
* 統合テストのロジックとci.ymlの設定が正しく機能するかどうかを確認してください。
* 統合テストが正しく実行され、期待通りの結果が得られるかどうかを確認してください。
* #345 
=> 統合テストロジックの実装 (#345)

.github/workflows/cd.yml
* EC2デプロイメントワークフローの改善と最適化を行い、より安定したデプロイメントプロセスを実現する。
* コンテナ名を 'minori_gin' から 'minori_gin_1' に変更
* ポートマッピングを 80:8080 から 8080:8080 に変更
* docker run コマンドから '--restart always' フラグを削除
* なし
* ポートマッピングの変更が現在の設定と互換性があるかどうか
* コンテナ名の変更が他の部分に影響を与えないか
* 更新されたワークフローでEC2インスタンスへの正常なデプロイメントが可能か
* 新しいポート設定（8080）でアプリケーションにアクセスできるか
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[タイトル](リンク)の形で添付してください。
* P3 : …
=> 💚 ci: EC2デプロイメントワークフローの更新

controllers/line_auth_controller.go, main.go, repositories/line_auth_repository.go, services/line_auth_services.go
- LINEログイン機能の一部が実装されました。今後の開発に向けて、テストを実施し、動作確認を行う必要があります。
- LINEログインの認証フローの一部が完了し、ユーザーがLINEアカウントでログインできるようになりました。
- 必要なテスト環境とテストコードを追加して、ログイン機能が意図した通りに動作するか確認します。
- 一部のAPIエンドポイントの設定がLINE認証フローに合わせて調整されました。
- 認証フローが正常に機能するか、エラーハンドリングの確認とテストのカバレッジをチェックしてください。
- テスト結果とAPIのレスポンス内容が適切であるか確認をお願いします。
- LINEログインの認証部分でユースケースに応じたテストシナリオを実行し、動作確認をお願いします。
- 特に認証フローの中で想定されるエラーが正しく処理されるかを確認してください。
- [LINEログインの実装](https://github.com/YJU-OKURA/project_minori-gin-deployment-repo/issues/349)
- 認証の成功/失敗のテスト結果を提供します。
- レビュアーはコードレビュー時に良いコードの方向性を示しますが、コード修正を強制することはありません。
- レビュアーは良いコードを見つけた場合、賞賛と励ましを惜しみません。
- レビューは特別なケースでない限り、レビュアーに指定された時点から3日以内に行ってください。
- コメント作成時にPrefixにP1、P2、P3を書いていただくと、Assigneeがより明確にコメントに対して対応することができます。
- P2 : …
=> LINEログインの実装

controllers/attendance_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, repositories/attendance_repository.go, repositories/class_schedule_repository.go, services/attendance_service.go
* 現在の出席管理システムでは、クラススケジュールIDベースでの出席追跡が不十分で、統計情報の取得が困難でした
* 時間関連のフィールド名が統一されておらず、コードの可読性と保守性が低下していました
* 出席情報の取得時に関連エンティティの事前読み込みが最適化されていませんでした
* 出席管理システムをCSIDベースの追跡に対応するようにリファクタリング
* CIDとCSIDベースの出席統計機能を追加
* クラススケジュールの時間フィールドを`started_at`/`ended_at`に統一
* APIエンドポイントの最適化と関連ドキュメントの更新
* 出席情報取得時の関連エンティティのPreload処理を追加
* Swagger関連ドキュメント（docs.go、swagger.json、swagger.yaml）の更新
* main.goのルーティング設定の更新
* 新しく追加した統計情報取得機能の実装方法の妥当性
* CSIDベースの出席管理への移行による影響
* 時間フィールド名の変更による既存機能への影響
* 出席統計情報取得機能の動作確認
* CSIDベースの出席情報の作成/更新/削除処理
* 時間フィールド名変更後のクラススケジュール関連機能の動作確認
* Preload処理追加後のパフォーマンス確認
* #325 
* …
=> ♻️ refactor: 出席管理システムの機能強化と CSID ベースの追跡機能を実装

controllers/attendance_controller.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go
* 既存の出席管理APIのルート構造が一貫性に欠け、RESTful APIの原則に完全に準拠していない問題がありました
* Swagger文書の記述が不十分で、API利用者にとって分かりにくい状態でした
* エラーレスポンスの形式が統一されておらず、クライアント側での処理が煩雑になっていました
* APIルートの構造をRESTful原則に基づいて統一（`/api/gin/attendances`をベースとした一貫性のある構造）
* 共通のレスポンス型（`SuccessResponse`、`ErrorResponse`）を導入し、レスポンス形式を標準化
* Swagger文書に詳細な説明、レスポンスモデル、エラーケースを追加
* エラーハンドリングの共通化と改善
* コードのログ出力を強化し、デバッグ時の可読性を向上
* テストケース追加の準備としてのインターフェース改善
* 新しいAPIルート構造が実際のユースケースに適しているか
* エラーレスポンスの形式が十分な情報を提供しているか
* Swagger文書の記述が API利用者にとって分かりやすいものになっているか
* 各エンドポイントの新しいルート構造での動作確認
* エラーケースでの適切なレスポンス返却の確認
* Swagger UIでの文書表示の確認
* クライアントアプリケーションとの互換性テスト
* #325 
* …
=> 出席管理APIのルート構造改善とSwagger文書の強化

repositories/attendance_repository.go
> 実装した機能や解決した課題、PRを開くきっかけや目的をReviewerが理解しやすいように書いてください。 
> バックログのリンク、ダイアグラム、Figmaなどの関連ドキュメントを添付するとより良いです。
* Attendance統計メソッドにおけるN+1問題を解決するため、Preloadを使用して関連データを事前にロードするように修正しました。
> 問題を解決しながら、主な変更点を書いてください。
* GetAttendanceStatisticsByCIDメソッドとGetAttendanceStatisticsByCSIDメソッドでPreloadを使用して関連するClassUserとUserデータを事前にロードするようにしました。
* データベースクエリの数を減らし、パフォーマンスを向上させました。
> ない場合は「なし」と記載してください。
* なし
> 開発過程で他の方の意見が気になったり、クロスチェックが必要だと感じたコードがあれば教えてください。
* Preloadの使用方法とその影響について確認をお願いします。
> テストが必要な項目やテストコードが追加されたら一緒に書いてください。
* Attendance統計メソッドの動作確認とパフォーマンステストをお願いします。
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[タイトル](リンク)の形で添付してください。
* Related issue: #356
* …
=> N+1問題を解決するためのAttendance統計メソッドの修正

repositories/attendance_repository.go, services/attendance_service.go
> 実装した機能や解決した課題、PRを開くきっかけや目的をReviewerが理解しやすいように書いてください。 
> バックログのリンク、ダイアグラム、Figmaなどの関連ドキュメントを添付するとより良いです。
* 出席情報取得時にユーザープロフィール画像のURLが正しく取得できない問題が発生していました。これにより、フロントエンド側でユーザーのプロフィール画像が表示されない状態となっていました。
> 問題を解決しながら、主な変更点を書いてください。
* `GetAllAttendancesByCID`と`GetAllAttendancesByCSID`関数にPreload関係を追加
- `ClassUser.User`
- `ClassUser.Class`
- `ClassSchedule.Class`
* リポジトリレイヤーから冗長な統計関数を削除
- `GetAttendanceStatisticsByCID`
- `GetAttendanceStatisticsByCSID`
* コードフォーマットの改善による可読性の向上
> ない場合は「なし」と記載してください。
* なし
> 開発過程で他の方の意見が気になったり、クロスチェックが必要だと感じたコードがあれば教えてください。
* Preloadの関係が適切に設定されているか
* 統計関数の削除による影響がないか
* パフォーマンスへの影響
> テストが必要な項目やテストコードが追加されたら一緒に書いてください。
* 出席情報取得時にユーザープロフィール画像が正しく表示されるか
* 関連するデータ（クラス情報、スケジュール情報）が正しく取得できているか
* 既存の機能に影響がないか
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[ …
=> ♻️ refactor: Enhance attendance preload relationships in repository

controllers/attendance_controller.go
> 実装した機能や解決した課題、PRを開くきっかけや目的をReviewerが理解しやすいように書いてください。 
> バックログのリンク、ダイアグラム、Figmaなどの関連ドキュメントを添付するとより良いです。
* 現在、`GetAttendancesBySchedule`および`GetAttendancesByClass`関数では、出席情報のカウントが存在しない場合にデフォルト値が設定されていません。そのため、カウントが存在しない場合に0を返すように修正する必要があります。
> 問題を解決しながら、主な変更点を書いてください。
* `controllers/attendance_controller.go`ファイルの`generateAttendanceResponse`関数を修正し、出席カウントのデフォルト値を0に設定しました。
> ない場合は「なし」と記載してください。
* なし
> 開発過程で他の方の意見が気になったり、クロスチェックが必要だと感じたコードがあれば教えてください。
* `generateAttendanceResponse`関数の修正が正しく行われているかどうか。
> テストが必要な項目やテストコードが追加されたら一緒に書いてください。
* 出席カウントが存在しない場合に0が返されることを確認するテストケース。
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[タイトル](リンク)の形で添付してください。
* Related issue: #359
* …
=> 出席カウントのデフォルト値を0に設定する
